<?php

namespace Database\Seeders;

use App\Models\Breed;
use Illuminate\Database\Seeder;

/**
 * A second batch, extending BreedSeeder rather than replacing it.
 *
 * Compiled from TICA, CFA, FIFe and GCCF breed standards, cross-checked
 * against vet references (PetMD, VCA). A handful of breeds turned up in
 * research but are deliberately left out here rather than seeded on
 * unreliable numbers: Cyprus Cat, Kanaani and Toybob had directly
 * conflicting weight figures between sources with no way to arbitrate,
 * Ojos Azules and York Chocolate are functionally dormant breeds with a
 * near-vanished population, Minskin and Aegean had too little independent
 * data to state a weight range with any confidence. Guessing a number for
 * any of them would look precise without being true.
 *
 * Ranges here lean toward the tighter, more consensus end where sources
 * disagreed, rather than the widest span found, which is a deliberate
 * choice to keep the data usable rather than technically unfalsifiable.
 */
class AdditionalBreedSeeder extends Seeder
{
    public function run(): void
    {
        $start = (int) (Breed::max('popularity_rank') ?? 0) + 1;

        foreach ($this->breeds() as $i => $breed) {
            Breed::updateOrCreate(
                ['slug' => $breed['slug']],
                $breed + ['popularity_rank' => $start + $i, 'is_active' => true]
            );
        }
    }

    private function breeds(): array
    {
        return [
            [
                'name' => 'American Bobtail', 'slug' => 'american-bobtail', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 3.5, 'weight_max_kg' => 6.8, 'coat_length' => 'short',
                'energy_level' => 3, 'affection_level' => 4, 'child_friendly' => 5, 'grooming_needs' => 2, 'shedding_level' => 3, 'intelligence' => 4,
                'lifespan_min' => 13, 'lifespan_max' => 15, 'health_watch' => ['Hip dysplasia', 'Spinal issues in some tailless individuals'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A naturally short-tailed breed developed from feral cats found in the American Southwest in the 1960s.',
                'temperament_summary' => 'Dog-like, highly trainable, sociable',
                'fun_fact' => 'American Bobtails are often noted for learning simple tricks and walking on a leash more readily than most breeds.',
            ],
            [
                'name' => 'American Curl', 'slug' => 'american-curl', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'small', 'weight_min_kg' => 2.3, 'weight_max_kg' => 4.5, 'coat_length' => 'medium',
                'energy_level' => 3, 'affection_level' => 4, 'child_friendly' => 4, 'grooming_needs' => 2, 'shedding_level' => 2, 'intelligence' => 3,
                'lifespan_min' => 12, 'lifespan_max' => 16, 'health_watch' => ['Prone to ear infections from the curled ear shape'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Named for ears that curl backward, from a spontaneous mutation found on a stray cat in California in 1981.',
                'temperament_summary' => 'Affectionate, playful, retains kitten-like curiosity',
                'fun_fact' => 'Kittens are born with straight ears; the curl sets in over the first few days and continues developing for months.',
            ],
            [
                'name' => 'American Wirehair', 'slug' => 'american-wirehair', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 4.0, 'weight_max_kg' => 7.0, 'coat_length' => 'short',
                'energy_level' => 3, 'affection_level' => 3, 'child_friendly' => 4, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 3,
                'lifespan_min' => 12, 'lifespan_max' => 18, 'health_watch' => ['Hypertrophic cardiomyopathy', 'Hip dysplasia'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A natural mutation first found on a New York farm in 1966 gives this breed a dense, springy, wire-textured coat.',
                'temperament_summary' => 'Easygoing, adaptable, low-maintenance',
                'fun_fact' => 'Every American Wirehair traces back to one barn kitten found in Vernon, New York.',
            ],
            [
                'name' => 'Arabian Mau', 'slug' => 'arabian-mau', 'origin_country' => 'Arabian Peninsula',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 3.5, 'weight_max_kg' => 6.0, 'coat_length' => 'short',
                'energy_level' => 4, 'affection_level' => 3, 'child_friendly' => 3, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 4,
                'lifespan_min' => 9, 'lifespan_max' => 14, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A naturally evolved desert landrace only formalized into a breed standard in the 2000s, shaped by generations surviving in a harsh climate.',
                'temperament_summary' => 'Hardy, alert, independent',
                'fun_fact' => 'Unlike most pedigreed breeds, the Arabian Mau was not deliberately bred; it developed on its own across the Arabian Peninsula over centuries.',
            ],
            [
                'name' => 'Australian Mist', 'slug' => 'australian-mist', 'origin_country' => 'Australia',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 3.5, 'weight_max_kg' => 7.0, 'coat_length' => 'short',
                'energy_level' => 3, 'affection_level' => 5, 'child_friendly' => 5, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 3,
                'lifespan_min' => 12, 'lifespan_max' => 18, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Developed in the 1970s and 80s from Burmese, Abyssinian and domestic shorthair stock, bred specifically for a gentle, tolerant temperament.',
                'temperament_summary' => 'Gentle, sociable, tolerant of handling',
                'fun_fact' => 'The breed was originally named the Spotted Mist, then renamed to reflect its Australian origin once more coat patterns were recognized.',
            ],
            [
                'name' => 'Balinese', 'slug' => 'balinese', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 3.5, 'weight_max_kg' => 6.0, 'coat_length' => 'long',
                'energy_level' => 5, 'affection_level' => 5, 'child_friendly' => 3, 'grooming_needs' => 2, 'shedding_level' => 2, 'intelligence' => 5,
                'lifespan_min' => 12, 'lifespan_max' => 18, 'health_watch' => ['Progressive retinal atrophy', 'Amyloidosis'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'The long-haired form of the Siamese, arising from a spontaneous coat mutation and sharing the same vocal, people-focused personality.',
                'temperament_summary' => 'Vocal and demanding, like a Siamese with a longer coat',
                'fun_fact' => 'Despite the name, the Balinese has no connection to Bali; breeders chose it for the flowing, dancer-like grace of the breed\'s movement.',
            ],
            [
                'name' => 'Bombay', 'slug' => 'bombay', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 2.7, 'weight_max_kg' => 6.8, 'coat_length' => 'short',
                'energy_level' => 3, 'affection_level' => 5, 'child_friendly' => 4, 'grooming_needs' => 1, 'shedding_level' => 1, 'intelligence' => 4,
                'lifespan_min' => 12, 'lifespan_max' => 18, 'health_watch' => ['Hypertrophic cardiomyopathy', 'Breathing difficulty in flatter-faced lines'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Bred in the 1950s and 60s by crossing Burmese with black American Shorthairs to create a cat resembling a miniature black panther.',
                'temperament_summary' => 'Affectionate, people-oriented, enjoys being carried',
                'fun_fact' => 'Every Bombay has a solid black coat with a patent-leather sheen and copper or gold eyes, no other color is recognized.',
            ],
            [
                'name' => 'British Longhair', 'slug' => 'british-longhair', 'origin_country' => 'United Kingdom',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => true,
                'size_category' => 'large', 'weight_min_kg' => 3.0, 'weight_max_kg' => 8.0, 'coat_length' => 'long',
                'energy_level' => 2, 'affection_level' => 3, 'child_friendly' => 4, 'grooming_needs' => 3, 'shedding_level' => 4, 'intelligence' => 3,
                'lifespan_min' => 12, 'lifespan_max' => 17, 'health_watch' => ['Prone to weight gain given a sedentary temperament'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'The long-haired variant of the British Shorthair, sharing the same stocky, round-faced build and placid nature under a longer coat.',
                'temperament_summary' => 'Calm, independent, undemanding',
                'fun_fact' => 'For decades the long-haired kittens that occasionally appeared in British Shorthair litters were not bred forward; the variant only gained its own standard more recently.',
            ],
            [
                'name' => 'Burmilla', 'slug' => 'burmilla', 'origin_country' => 'United Kingdom',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 3.0, 'weight_max_kg' => 6.0, 'coat_length' => 'short',
                'energy_level' => 3, 'affection_level' => 4, 'child_friendly' => 4, 'grooming_needs' => 2, 'shedding_level' => 2, 'intelligence' => 4,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => ['Polycystic kidney disease'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Originated from an accidental 1981 mating between a Burmese and a Chinchilla Persian in the United Kingdom.',
                'temperament_summary' => 'Playful, sociable, retains a Burmese-like curiosity',
                'fun_fact' => 'The pairing that founded the breed was unplanned; the resulting kittens\' shimmering, tipped coat won breeders over anyway.',
            ],
            [
                'name' => 'Chartreux', 'slug' => 'chartreux', 'origin_country' => 'France',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 2.7, 'weight_max_kg' => 6.3, 'coat_length' => 'short',
                'energy_level' => 2, 'affection_level' => 4, 'child_friendly' => 4, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 3,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => ['Patellar luxation'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'An old French natural breed, sometimes called France\'s unofficial national cat, with a dense blue-grey coat and a distinctive "smiling" expression.',
                'temperament_summary' => 'Quiet, loyal, close to silent even when vocalizing',
                'fun_fact' => 'Chartreux cats are known for a near-silent meow; many owners describe theirs as barely vocal at all.',
            ],
            [
                'name' => 'Chausie', 'slug' => 'chausie', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'large', 'weight_min_kg' => 6.8, 'weight_max_kg' => 11.3, 'coat_length' => 'short',
                'energy_level' => 5, 'affection_level' => 3, 'child_friendly' => 2, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 5,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => ['Hypertrophic cardiomyopathy'], 'hypoallergenic' => false,
                'good_for_apartments' => false, 'good_for_beginners' => false,
                'description' => 'A hybrid of the wild jungle cat and domestic cats, most often Abyssinians, finalized as a breed in the 1990s.',
                'temperament_summary' => 'Highly active, needs real space and an experienced owner',
                'fun_fact' => 'Chausies are strong jumpers, capable of clearing six feet from a standing position.',
            ],
            [
                'name' => 'Colorpoint Shorthair', 'slug' => 'colorpoint-shorthair', 'origin_country' => 'United States',
                'registry_tica' => false, 'registry_cfa' => true, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 2.5, 'weight_max_kg' => 5.0, 'coat_length' => 'short',
                'energy_level' => 5, 'affection_level' => 5, 'child_friendly' => 3, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 5,
                'lifespan_min' => 12, 'lifespan_max' => 16, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'Essentially a Siamese-type cat in point colors outside the traditional four, given its own CFA breed status in 1964.',
                'temperament_summary' => 'Vocal, intelligent, forms close one-person bonds',
                'fun_fact' => 'The breed exists mainly as a classification: it is built to the Siamese standard in every way except the color of its points.',
            ],
            [
                'name' => 'Cornish Rex', 'slug' => 'cornish-rex', 'origin_country' => 'United Kingdom',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'small', 'weight_min_kg' => 2.5, 'weight_max_kg' => 4.5, 'coat_length' => 'short',
                'energy_level' => 5, 'affection_level' => 5, 'child_friendly' => 4, 'grooming_needs' => 1, 'shedding_level' => 1, 'intelligence' => 4,
                'lifespan_min' => 11, 'lifespan_max' => 15, 'health_watch' => ['Progressive retinal atrophy', 'Hypertrophic cardiomyopathy', 'Patellar luxation'], 'hypoallergenic' => true,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Arose from a spontaneous curly-coat mutation in Cornwall, England in 1950, producing a fine, wavy coat with no guard hairs and a very slim, athletic build.',
                'temperament_summary' => 'Energetic, playful, seeks out warmth',
                'fun_fact' => 'With no outer guard hairs, the Cornish Rex\'s coat sheds unusually little, which is why it is often suggested to people with mild cat allergies.',
            ],
            [
                'name' => 'Cymric', 'slug' => 'cymric', 'origin_country' => 'Canada',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 3.0, 'weight_max_kg' => 5.5, 'coat_length' => 'long',
                'energy_level' => 3, 'affection_level' => 4, 'child_friendly' => 4, 'grooming_needs' => 3, 'shedding_level' => 3, 'intelligence' => 3,
                'lifespan_min' => 10, 'lifespan_max' => 15, 'health_watch' => ['Manx syndrome, affecting the spine and nerves'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'The long-haired variant of the Manx, sharing the same natural taillessness and rounded, sturdy body.',
                'temperament_summary' => 'Loyal, playful, strong hind legs make them good jumpers',
                'fun_fact' => 'Like the Manx, Cymric tail length varies naturally from a full stub to none at all.',
            ],
            [
                'name' => 'Donskoy', 'slug' => 'donskoy', 'origin_country' => 'Russia',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 3.0, 'weight_max_kg' => 6.0, 'coat_length' => 'hairless',
                'energy_level' => 4, 'affection_level' => 5, 'child_friendly' => 4, 'grooming_needs' => 4, 'shedding_level' => 1, 'intelligence' => 4,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => ['Feline ectodermal dysplasia', 'Sun sensitivity'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'A Russian hairless breed from a spontaneous 1987 mutation, genetically distinct from the Sphynx despite the similar look.',
                'temperament_summary' => 'Affectionate, seeks out warmth, sociable',
                'fun_fact' => 'Unlike the Sphynx\'s recessive hairless gene, the Donskoy\'s is dominant, which is part of why the two breeds developed independently.',
            ],
            [
                'name' => 'Egyptian Mau', 'slug' => 'egyptian-mau', 'origin_country' => 'Egypt',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 3.6, 'weight_max_kg' => 5.4, 'coat_length' => 'short',
                'energy_level' => 5, 'affection_level' => 4, 'child_friendly' => 3, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 4,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => ['Bladder stones', 'Pyruvate kinase deficiency'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'One of the few naturally spotted breeds, with a coat pattern found on cats depicted in ancient Egyptian art.',
                'temperament_summary' => 'Athletic, reserved with strangers, deeply bonded to family',
                'fun_fact' => 'The Egyptian Mau is reputed to be the fastest domestic cat breed, with a running speed cited up to 30 miles per hour.',
            ],
            [
                'name' => 'European Shorthair', 'slug' => 'european-shorthair', 'origin_country' => 'Continental Europe',
                'registry_tica' => false, 'registry_cfa' => false, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 3.6, 'weight_max_kg' => 7.0, 'coat_length' => 'short',
                'energy_level' => 3, 'affection_level' => 3, 'child_friendly' => 4, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 3,
                'lifespan_min' => 12, 'lifespan_max' => 17, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A natural landrace descended from European working cats, formally distinguished from the British Shorthair by FIFe in 1982.',
                'temperament_summary' => 'Hardy, independent, generally robust health',
                'fun_fact' => 'Because it developed naturally across the continent rather than through selective breeding, the European Shorthair still closely resembles the average domestic cat.',
            ],
            [
                'name' => 'Havana Brown', 'slug' => 'havana-brown', 'origin_country' => 'United Kingdom',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 3.6, 'weight_max_kg' => 4.5, 'coat_length' => 'short',
                'energy_level' => 4, 'affection_level' => 5, 'child_friendly' => 4, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 4,
                'lifespan_min' => 10, 'lifespan_max' => 15, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Developed in the UK in the 1950s by crossing Siamese with domestic black cats to fix a rich, even mahogany-brown coat.',
                'temperament_summary' => 'Curious, uses its paws to investigate, sociable',
                'fun_fact' => 'The breed is named for its coat color, resembling Havana cigar tobacco, not for any connection to Cuba.',
            ],
            [
                'name' => 'Highlander', 'slug' => 'highlander', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'large', 'weight_min_kg' => 4.5, 'weight_max_kg' => 9.0, 'coat_length' => 'short',
                'energy_level' => 4, 'affection_level' => 4, 'child_friendly' => 4, 'grooming_needs' => 2, 'shedding_level' => 2, 'intelligence' => 4,
                'lifespan_min' => 10, 'lifespan_max' => 16, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A recently developed breed, still working toward full recognition, known for curled ears and a naturally bobbed tail.',
                'temperament_summary' => 'Playful, dog-like, enjoys water more than most cats',
                'fun_fact' => 'The Highlander\'s curled ears are a different, independently arising trait from the similar-looking American Curl.',
            ],
            [
                'name' => 'Japanese Bobtail', 'slug' => 'japanese-bobtail', 'origin_country' => 'Japan',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 2.5, 'weight_max_kg' => 4.5, 'coat_length' => 'short',
                'energy_level' => 4, 'affection_level' => 5, 'child_friendly' => 5, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 4,
                'lifespan_min' => 12, 'lifespan_max' => 16, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'An ancient breed depicted in Japanese art for over a thousand years, with a naturally short, pom-pom-like tail.',
                'temperament_summary' => 'Sociable, vocal, described by owners as talkative',
                'fun_fact' => 'The beckoning maneki-neko figure common in Japanese shops and restaurants is widely believed to be modeled on this breed.',
            ],
            [
                'name' => 'Javanese', 'slug' => 'javanese', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 2.3, 'weight_max_kg' => 5.4, 'coat_length' => 'long',
                'energy_level' => 5, 'affection_level' => 5, 'child_friendly' => 3, 'grooming_needs' => 2, 'shedding_level' => 2, 'intelligence' => 5,
                'lifespan_min' => 10, 'lifespan_max' => 15, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'The Oriental-pattern counterpart to the Balinese, sharing its long coat; some registries, including the CFA, now treat it as a Balinese color division rather than a fully separate breed.',
                'temperament_summary' => 'Vocal, active, closely bonded to their people',
                'fun_fact' => 'Despite the name, the Javanese has no connection to the island of Java; it was named to fit alongside the similarly Indonesia-inspired Balinese.',
            ],
            [
                'name' => 'Khao Manee', 'slug' => 'khao-manee', 'origin_country' => 'Thailand',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 2.5, 'weight_max_kg' => 5.0, 'coat_length' => 'short',
                'energy_level' => 4, 'affection_level' => 4, 'child_friendly' => 4, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 4,
                'lifespan_min' => 10, 'lifespan_max' => 15, 'health_watch' => ['Congenital deafness, especially in blue-eyed cats', 'Sunburn risk from the white coat'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'An ancient Thai breed mentioned in 14th-century poetry, traditionally prized as a good-luck cat for Thai royalty.',
                'temperament_summary' => 'Alert, sociable, thrives on attention',
                'fun_fact' => 'The name means "white gem" in Thai, a reference to its all-white coat.',
            ],
            [
                'name' => 'Korat', 'slug' => 'korat', 'origin_country' => 'Thailand',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'small', 'weight_min_kg' => 2.5, 'weight_max_kg' => 4.5, 'coat_length' => 'short',
                'energy_level' => 4, 'affection_level' => 4, 'child_friendly' => 3, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 4,
                'lifespan_min' => 10, 'lifespan_max' => 15, 'health_watch' => ['GM1 gangliosidosis, a screenable genetic condition'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'An ancient, naturally silver-blue Thai breed considered a symbol of good luck, historically never crossbred with other breeds.',
                'temperament_summary' => 'Observant, bonds closely, can be reserved with strangers',
                'fun_fact' => 'In Thailand, pairs of Korats were traditionally given as wedding gifts to bring good fortune to a marriage.',
            ],
            [
                'name' => 'Kurilian Bobtail', 'slug' => 'kurilian-bobtail', 'origin_country' => 'Russia',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 3.6, 'weight_max_kg' => 6.8, 'coat_length' => 'short',
                'energy_level' => 4, 'affection_level' => 4, 'child_friendly' => 4, 'grooming_needs' => 2, 'shedding_level' => 3, 'intelligence' => 4,
                'lifespan_min' => 15, 'lifespan_max' => 18, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A naturally bobtailed breed from Russia\'s Kuril Islands, prized for hardiness and a reputed strong instinct for fishing.',
                'temperament_summary' => 'Hardy, confident, reportedly enjoys water',
                'fun_fact' => 'Each Kurilian Bobtail\'s tail is unique, made up of kinks and curves rather than a single uniform shape.',
            ],
            [
                'name' => 'LaPerm', 'slug' => 'laperm', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 2.5, 'weight_max_kg' => 5.5, 'coat_length' => 'medium',
                'energy_level' => 4, 'affection_level' => 5, 'child_friendly' => 4, 'grooming_needs' => 2, 'shedding_level' => 2, 'intelligence' => 4,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => null, 'hypoallergenic' => true,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Arose from a spontaneous curly-coat mutation on an Oregon farm in 1982, ranging from loose waves to tight ringlets.',
                'temperament_summary' => 'Affectionate, curious, enjoys being close to people',
                'fun_fact' => 'LaPerm kittens are usually born bald or with a straight coat and grow into their curls over the following months.',
            ],
            [
                'name' => 'Lykoi', 'slug' => 'lykoi', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'small', 'weight_min_kg' => 2.7, 'weight_max_kg' => 4.5, 'coat_length' => 'hairless',
                'energy_level' => 4, 'affection_level' => 4, 'child_friendly' => 3, 'grooming_needs' => 3, 'shedding_level' => 1, 'intelligence' => 4,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => ['Skin sensitivity', 'Cold sensitivity'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'A very recently recognized breed, from a natural mutation causing a partial, patchy coat that gives it a distinctive "werewolf" look.',
                'temperament_summary' => 'Active, described by owners as more dog-like than most breeds',
                'fun_fact' => 'The name comes from the Greek word for wolf, "lykos," a nod to the breed\'s appearance.',
            ],
            [
                'name' => 'Munchkin', 'slug' => 'munchkin', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'small', 'weight_min_kg' => 2.5, 'weight_max_kg' => 4.5, 'coat_length' => 'short',
                'energy_level' => 4, 'affection_level' => 4, 'child_friendly' => 4, 'grooming_needs' => 2, 'shedding_level' => 2, 'intelligence' => 3,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => ['Lordosis, a spinal curvature', 'Pectus excavatum', 'Osteoarthritis'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Known for a dominant gene that shortens the legs; some registries, including the CFA, decline to recognize the breed over welfare concerns.',
                'temperament_summary' => 'Playful, energetic, does not act limited by short legs',
                'fun_fact' => 'Despite the short legs, Munchkins are capable runners and jumpers, just with a different gait than most cats.',
            ],
            [
                'name' => 'Napoleon', 'slug' => 'napoleon', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'small', 'weight_min_kg' => 2.3, 'weight_max_kg' => 4.5, 'coat_length' => 'short',
                'energy_level' => 3, 'affection_level' => 5, 'child_friendly' => 5, 'grooming_needs' => 2, 'shedding_level' => 2, 'intelligence' => 3,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => ['Shares the Munchkin\'s spinal and joint risk in short-legged lines'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A dwarf breed combining Munchkin with Persian, Himalayan or Exotic lines; TICA renamed it the Minuet in 2015.',
                'temperament_summary' => 'Sweet-natured, calm, enjoys company',
                'fun_fact' => 'The original name honored Napoleon Bonaparte, chosen for the breed\'s short stature.',
            ],
            [
                'name' => 'Nebelung', 'slug' => 'nebelung', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 3.0, 'weight_max_kg' => 5.5, 'coat_length' => 'long',
                'energy_level' => 3, 'affection_level' => 4, 'child_friendly' => 3, 'grooming_needs' => 3, 'shedding_level' => 3, 'intelligence' => 4,
                'lifespan_min' => 15, 'lifespan_max' => 18, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A blue-coated, long-haired relative of the Russian Blue, developed in the 1980s and sharing its reserved, loyal nature.',
                'temperament_summary' => 'Reserved with strangers, deeply attached to family',
                'fun_fact' => 'The name means "creature of the mist" in German, chosen for the shimmering, silver-tipped quality of the coat.',
            ],
            [
                'name' => 'Ocicat', 'slug' => 'ocicat', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 3.0, 'weight_max_kg' => 6.5, 'coat_length' => 'short',
                'energy_level' => 4, 'affection_level' => 5, 'child_friendly' => 4, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 5,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => ['Progressive retinal atrophy', 'Renal amyloidosis'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A spotted, wild-looking but fully domestic breed from Siamese and Abyssinian crosses, first bred by accident in 1964.',
                'temperament_summary' => 'Outgoing, trainable, often described as dog-like',
                'fun_fact' => 'The Ocicat is named for its resemblance to the wild ocelot, despite having no wildcat ancestry at all.',
            ],
            [
                'name' => 'Oriental Longhair', 'slug' => 'oriental-longhair', 'origin_country' => 'United Kingdom',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'small', 'weight_min_kg' => 2.3, 'weight_max_kg' => 4.5, 'coat_length' => 'long',
                'energy_level' => 5, 'affection_level' => 5, 'child_friendly' => 3, 'grooming_needs' => 2, 'shedding_level' => 2, 'intelligence' => 5,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'The long-haired counterpart to the Oriental Shorthair, sharing the same slender body and vocal, attention-seeking personality.',
                'temperament_summary' => 'Vocal, demanding of attention, bonds intensely with owners',
                'fun_fact' => 'Like its shorthaired relative, the Oriental Longhair comes in an unusually wide range of recognized colors and patterns.',
            ],
            [
                'name' => 'Peterbald', 'slug' => 'peterbald', 'origin_country' => 'Russia',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 2.0, 'weight_max_kg' => 5.0, 'coat_length' => 'hairless',
                'energy_level' => 4, 'affection_level' => 5, 'child_friendly' => 4, 'grooming_needs' => 4, 'shedding_level' => 1, 'intelligence' => 4,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => ['Feline ectodermal dysplasia', 'Sun sensitivity when hairless'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'Developed in St. Petersburg in 1994 from a Donskoy and Oriental Shorthair cross; coat can range from fully bald to a fine, brush-like texture.',
                'temperament_summary' => 'Sociable, affectionate, seeks out warmth',
                'fun_fact' => 'A single Peterbald litter can include kittens across the full range from bald to a soft, velour-like coat.',
            ],
            [
                'name' => 'Pixie-bob', 'slug' => 'pixie-bob', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'large', 'weight_min_kg' => 3.6, 'weight_max_kg' => 7.7, 'coat_length' => 'short',
                'energy_level' => 3, 'affection_level' => 4, 'child_friendly' => 4, 'grooming_needs' => 2, 'shedding_level' => 3, 'intelligence' => 4,
                'lifespan_min' => 13, 'lifespan_max' => 15, 'health_watch' => ['Prone to weight gain'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Bred to resemble a bobcat, with a bobbed tail and spotted coat; despite marketing claims of wild ancestry, it is a fully domestic breed.',
                'temperament_summary' => 'Dog-like, trainable, often described as loyal to one household',
                'fun_fact' => 'Some Pixie-bobs are naturally polydactyl, born with extra toes.',
            ],
            [
                'name' => 'Selkirk Rex', 'slug' => 'selkirk-rex', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 4.1, 'weight_max_kg' => 7.3, 'coat_length' => 'medium',
                'energy_level' => 3, 'affection_level' => 5, 'child_friendly' => 5, 'grooming_needs' => 3, 'shedding_level' => 3, 'intelligence' => 3,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'From a spontaneous curly-coat mutation found in Montana in 1987, this breed is the only one named after a person, its founder\'s stepfather.',
                'temperament_summary' => 'Patient, tolerant, good with children',
                'fun_fact' => 'Selkirk Rex kittens can be born with straight or curly coats within the same litter, and the curl can change over a cat\'s first two years.',
            ],
            [
                'name' => 'Serengeti', 'slug' => 'serengeti', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 4.0, 'weight_max_kg' => 7.0, 'coat_length' => 'short',
                'energy_level' => 5, 'affection_level' => 3, 'child_friendly' => 3, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 5,
                'lifespan_min' => 10, 'lifespan_max' => 15, 'health_watch' => ['Hypertrophic cardiomyopathy', 'Polycystic kidney disease'], 'hypoallergenic' => false,
                'good_for_apartments' => false, 'good_for_beginners' => false,
                'description' => 'Created from Oriental Shorthair and Bengal crosses to mimic the look of an African serval, with no wild ancestry at all.',
                'temperament_summary' => 'Active, vocal, needs space to run and climb',
                'fun_fact' => 'Serengetis were bred specifically for long legs and tall, rounded ears, aiming for the serval\'s look through selective breeding alone.',
            ],
            [
                'name' => 'Singapura', 'slug' => 'singapura', 'origin_country' => 'Singapore',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'small', 'weight_min_kg' => 1.8, 'weight_max_kg' => 3.6, 'coat_length' => 'short',
                'energy_level' => 4, 'affection_level' => 5, 'child_friendly' => 4, 'grooming_needs' => 1, 'shedding_level' => 1, 'intelligence' => 4,
                'lifespan_min' => 11, 'lifespan_max' => 15, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Developed from Singapore street cats in the 1970s, and recognized by Guinness World Records as the smallest domestic cat breed.',
                'temperament_summary' => 'Curious, playful, big personality for a small cat',
                'fun_fact' => 'The breed\'s nickname, "drain cat," comes from its ancestors, which were known to shelter in Singapore\'s storm drains.',
            ],
            [
                'name' => 'Snowshoe', 'slug' => 'snowshoe', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 3.1, 'weight_max_kg' => 6.5, 'coat_length' => 'short',
                'energy_level' => 4, 'affection_level' => 5, 'child_friendly' => 4, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 4,
                'lifespan_min' => 14, 'lifespan_max' => 18, 'health_watch' => ['Hypertrophic cardiomyopathy', 'Polycystic kidney disease'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A Siamese and American Shorthair cross from the 1960s, known for white "socked" paws on a color-point coat.',
                'temperament_summary' => 'Sociable, vocal but softer-voiced than a Siamese',
                'fun_fact' => 'No two Snowshoes have identical white markings, which makes each cat\'s pattern effectively unique.',
            ],
            [
                'name' => 'Sokoke', 'slug' => 'sokoke', 'origin_country' => 'Kenya',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 2.5, 'weight_max_kg' => 5.0, 'coat_length' => 'short',
                'energy_level' => 4, 'affection_level' => 3, 'child_friendly' => 3, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 4,
                'lifespan_min' => 12, 'lifespan_max' => 16, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'A naturally occurring breed from Kenya\'s Arabuko-Sokoke forest, and among the rarest cat breeds in the world.',
                'temperament_summary' => 'Independent, athletic, retains a wild-cat wariness of strangers',
                'fun_fact' => 'The global Sokoke population remains small enough that the breed is still considered at risk of disappearing entirely.',
            ],
            [
                'name' => 'Somali', 'slug' => 'somali', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 3.6, 'weight_max_kg' => 5.4, 'coat_length' => 'long',
                'energy_level' => 5, 'affection_level' => 4, 'child_friendly' => 3, 'grooming_needs' => 3, 'shedding_level' => 3, 'intelligence' => 5,
                'lifespan_min' => 11, 'lifespan_max' => 15, 'health_watch' => ['Pyruvate kinase deficiency', 'Progressive retinal atrophy'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'The long-haired variant of the Abyssinian, arising from a recessive gene and sharing the same active, inquisitive temperament under a fuller coat.',
                'temperament_summary' => 'Athletic, curious, in near-constant motion',
                'fun_fact' => 'Like the Abyssinian, each hair on a Somali carries several bands of color, giving the coat its shimmering, foxlike look.',
            ],
            [
                'name' => 'Thai', 'slug' => 'thai', 'origin_country' => 'Thailand',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 3.6, 'weight_max_kg' => 6.8, 'coat_length' => 'short',
                'energy_level' => 4, 'affection_level' => 5, 'child_friendly' => 3, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 5,
                'lifespan_min' => 12, 'lifespan_max' => 16, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'The original, moderately built Siamese-type cat from Thailand, preserved as its own breed after the modern Siamese was bred toward a more extreme, wedge-shaped standard.',
                'temperament_summary' => 'Vocal and people-focused, slightly less extreme in build than a modern Siamese',
                'fun_fact' => 'This breed is essentially what the Siamese looked like before decades of Western show breeding changed the standard.',
            ],
            [
                'name' => 'Toyger', 'slug' => 'toyger', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 3.6, 'weight_max_kg' => 6.8, 'coat_length' => 'short',
                'energy_level' => 4, 'affection_level' => 4, 'child_friendly' => 4, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 4,
                'lifespan_min' => 10, 'lifespan_max' => 15, 'health_watch' => ['Hypertrophic cardiomyopathy'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Bred purely for a cosmetic resemblance to a tiger through striped tabby patterning, with a fully domestic temperament.',
                'temperament_summary' => 'Sociable, active, no wilder in nature than any tabby',
                'fun_fact' => 'Toyger breeders have cited raising awareness of tiger conservation as part of the breed\'s original motivation.',
            ],
            [
                'name' => 'Turkish Van', 'slug' => 'turkish-van', 'origin_country' => 'Turkey',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'large', 'weight_min_kg' => 3.2, 'weight_max_kg' => 9.0, 'coat_length' => 'long',
                'energy_level' => 4, 'affection_level' => 4, 'child_friendly' => 4, 'grooming_needs' => 2, 'shedding_level' => 3, 'intelligence' => 4,
                'lifespan_min' => 12, 'lifespan_max' => 17, 'health_watch' => ['Hypertrophic cardiomyopathy'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'An ancient regional breed from eastern Turkey, unusual among cats for a genuine fondness for water and swimming.',
                'temperament_summary' => 'Athletic, bold, often drawn to water',
                'fun_fact' => 'The breed\'s water-resistant coat is part of what lets it swim comfortably, a trait rare enough that it is sometimes called "the swimming cat."',
            ],
        ];
    }
}
