<?php

namespace Database\Seeders;

use App\Models\Breed;
use Illuminate\Database\Seeder;

/**
 * Seeds the real, recognized cat breeds this site already trusts elsewhere:
 * the same set the cat age calculator's breed dropdown uses (config/cat-
 * breeds.php), extended here with the physical measurements, trait ratings
 * and registry recognition the admin breeds section needs.
 *
 * Weight ranges, coat type and origin are the commonly published figures
 * for each breed (CFA/TICA breed standards and veterinary breed guides).
 * Trait ratings (1 low to 5 high) reflect the general consensus in those
 * same published breed profiles, not a guess per row.
 */
class BreedSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->breeds() as $rank => $breed) {
            Breed::updateOrCreate(
                ['slug' => $breed['slug']],
                $breed + ['popularity_rank' => $rank + 1, 'is_active' => true]
            );
        }
    }

    private function breeds(): array
    {
        return [
            [
                'name' => 'Domestic Shorthair', 'slug' => 'domestic-shorthair', 'origin_country' => 'Worldwide',
                'registry_tica' => false, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 3.5, 'weight_max_kg' => 5.5, 'coat_length' => 'short',
                'energy_level' => 3, 'affection_level' => 3, 'child_friendly' => 4, 'grooming_needs' => 1, 'shedding_level' => 3, 'intelligence' => 3,
                'lifespan_min' => 12, 'lifespan_max' => 18, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Not a pedigreed breed but a genetic mix, and the most common cat in North America. Build, coat and temperament vary widely from one cat to the next.',
                'temperament_summary' => 'Varied: usually adaptable and easygoing',
                'fun_fact' => 'Most cats in US shelters are domestic shorthairs, which is why they are the least expensive cat to adopt and often the healthiest, thanks to a wide gene pool.',
            ],
            [
                'name' => 'Domestic Longhair', 'slug' => 'domestic-longhair', 'origin_country' => 'Worldwide',
                'registry_tica' => false, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 3.5, 'weight_max_kg' => 5.5, 'coat_length' => 'long',
                'energy_level' => 3, 'affection_level' => 3, 'child_friendly' => 4, 'grooming_needs' => 3, 'shedding_level' => 4, 'intelligence' => 3,
                'lifespan_min' => 12, 'lifespan_max' => 18, 'health_watch' => null, 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'The long-coated counterpart to the domestic shorthair: a genetic mix rather than a pedigreed breed, needing more brushing than its short-coated relative.',
                'temperament_summary' => 'Varied: usually adaptable and easygoing',
                'fun_fact' => 'The long-hair trait is recessive, so it shows up less often than short hair even in mixed populations that carry the gene.',
            ],
            [
                'name' => 'Abyssinian', 'slug' => 'abyssinian', 'origin_country' => 'United Kingdom',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 3.0, 'weight_max_kg' => 5.0, 'coat_length' => 'short',
                'energy_level' => 5, 'affection_level' => 4, 'child_friendly' => 3, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 5,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => ['Pyruvate kinase deficiency', 'Progressive retinal atrophy'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'A slim, ticked-coat breed developed in Britain in the 1800s, despite a name that points to Ethiopia. Constantly in motion and happiest with something to climb or chase.',
                'temperament_summary' => 'Athletic, curious, almost dog-like in following owners around',
                'fun_fact' => 'Each hair on an Abyssinian carries several bands of color, a pattern called ticking, which is what gives the coat its shimmering, agouti look.',
            ],
            [
                'name' => 'American Shorthair', 'slug' => 'american-shorthair', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 3.5, 'weight_max_kg' => 7.0, 'coat_length' => 'short',
                'energy_level' => 3, 'affection_level' => 3, 'child_friendly' => 5, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 3,
                'lifespan_min' => 15, 'lifespan_max' => 20, 'health_watch' => ['Hypertrophic cardiomyopathy'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Descended from working cats brought over on early American ships to control rodents, bred since into a sturdy, even-tempered companion.',
                'temperament_summary' => 'Easygoing, low-maintenance, good with families',
                'fun_fact' => 'One American Shorthair, a cat named Whittington, is documented as having sailed to America on the Mayflower in 1620.',
            ],
            [
                'name' => 'Bengal', 'slug' => 'bengal', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => true,
                'size_category' => 'large', 'weight_min_kg' => 4.0, 'weight_max_kg' => 8.0, 'coat_length' => 'short',
                'energy_level' => 5, 'affection_level' => 3, 'child_friendly' => 3, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 5,
                'lifespan_min' => 12, 'lifespan_max' => 16, 'health_watch' => ['Hypertrophic cardiomyopathy', 'Progressive retinal atrophy'], 'hypoallergenic' => false,
                'good_for_apartments' => false, 'good_for_beginners' => false,
                'description' => 'Developed by crossing domestic cats with the Asian leopard cat, bred down over generations to a companion animal with a wild, spotted coat.',
                'temperament_summary' => 'High-energy, athletic, needs real space and stimulation',
                'fun_fact' => 'Many Bengals genuinely enjoy water, unlike most cats, a trait some breeders trace back to the Asian leopard cat in their ancestry.',
            ],
            [
                'name' => 'Birman', 'slug' => 'birman', 'origin_country' => 'Myanmar',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 4.0, 'weight_max_kg' => 7.0, 'coat_length' => 'medium',
                'energy_level' => 2, 'affection_level' => 5, 'child_friendly' => 5, 'grooming_needs' => 3, 'shedding_level' => 3, 'intelligence' => 3,
                'lifespan_min' => 12, 'lifespan_max' => 16, 'health_watch' => ['Hypertrophic cardiomyopathy'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A silky, medium-length coat with color-point markings and signature white "gloves" on all four paws distinguish this calm, sociable breed.',
                'temperament_summary' => 'Gentle, quiet, attaches closely to family',
                'fun_fact' => 'Every Birman is born with a white coat; the color points develop gradually over the first two years.',
            ],
            [
                'name' => 'British Shorthair', 'slug' => 'british-shorthair', 'origin_country' => 'United Kingdom',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'large', 'weight_min_kg' => 4.0, 'weight_max_kg' => 8.0, 'coat_length' => 'short',
                'energy_level' => 2, 'affection_level' => 3, 'child_friendly' => 4, 'grooming_needs' => 2, 'shedding_level' => 3, 'intelligence' => 3,
                'lifespan_min' => 12, 'lifespan_max' => 17, 'health_watch' => ['Hypertrophic cardiomyopathy', 'Polycystic kidney disease'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A dense, plush coat over a stocky, round-faced build, dating back to cats the Romans brought to Britain. Content to observe rather than climb.',
                'temperament_summary' => 'Calm, independent, undemanding',
                'fun_fact' => 'The Cheshire Cat in Lewis Carroll\'s Alice in Wonderland is widely thought to be modeled on the British Shorthair\'s round face and grin.',
            ],
            [
                'name' => 'Burmese', 'slug' => 'burmese', 'origin_country' => 'Myanmar',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 3.5, 'weight_max_kg' => 6.0, 'coat_length' => 'short',
                'energy_level' => 4, 'affection_level' => 5, 'child_friendly' => 4, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 4,
                'lifespan_min' => 16, 'lifespan_max' => 18, 'health_watch' => ['Diabetes mellitus', 'Hypokalaemia'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A compact, muscular breed descended from a single brown cat brought from Burma to the US in the 1930s, known for staying close to their people.',
                'temperament_summary' => 'People-oriented, playful well into adulthood',
                'fun_fact' => 'Every Burmese alive today traces back to one cat, Wong Mau, imported to San Francisco in 1930.',
            ],
            [
                'name' => 'Devon Rex', 'slug' => 'devon-rex', 'origin_country' => 'United Kingdom',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'small', 'weight_min_kg' => 2.5, 'weight_max_kg' => 4.5, 'coat_length' => 'short',
                'energy_level' => 5, 'affection_level' => 5, 'child_friendly' => 4, 'grooming_needs' => 1, 'shedding_level' => 1, 'intelligence' => 4,
                'lifespan_min' => 14, 'lifespan_max' => 17, 'health_watch' => ['Patellar luxation', 'Hereditary myopathy'], 'hypoallergenic' => true,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Large ears, a pixie-like face and a soft, wavy coat from a natural genetic mutation found in Devon, England, in the 1960s.',
                'temperament_summary' => 'Mischievous, sociable, follows owners room to room',
                'fun_fact' => 'The Devon Rex\'s wavy coat is so fine that it sheds very little, which is why the breed is often suggested to people with mild cat allergies.',
            ],
            [
                'name' => 'Exotic Shorthair', 'slug' => 'exotic-shorthair', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 3.5, 'weight_max_kg' => 6.5, 'coat_length' => 'short',
                'energy_level' => 2, 'affection_level' => 4, 'child_friendly' => 4, 'grooming_needs' => 2, 'shedding_level' => 3, 'intelligence' => 2,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => ['Flat-faced breathing difficulty', 'Polycystic kidney disease'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Bred by crossing Persians with American Shorthairs, keeping the Persian\'s flat face and calm nature in a coat that needs far less brushing.',
                'temperament_summary' => 'Quiet, affectionate, low activity',
                'fun_fact' => 'Breeders nicknamed the Exotic Shorthair "the lazy man\'s Persian" for giving a similar look and temperament with a fraction of the grooming.',
            ],
            [
                'name' => 'Himalayan', 'slug' => 'himalayan', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 3.5, 'weight_max_kg' => 5.5, 'coat_length' => 'long',
                'energy_level' => 2, 'affection_level' => 4, 'child_friendly' => 3, 'grooming_needs' => 5, 'shedding_level' => 4, 'intelligence' => 2,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => ['Polycystic kidney disease', 'Flat-faced breathing difficulty'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'A Persian body and coat with the color-point pattern and blue eyes bred in from the Siamese, developed in the US in the 1950s.',
                'temperament_summary' => 'Gentle and placid, needs daily brushing',
                'fun_fact' => 'The Himalayan is classed as a Persian color division by the CFA rather than a fully separate breed.',
            ],
            [
                'name' => 'Maine Coon', 'slug' => 'maine-coon', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'large', 'weight_min_kg' => 4.5, 'weight_max_kg' => 11.0, 'coat_length' => 'long',
                'energy_level' => 3, 'affection_level' => 4, 'child_friendly' => 5, 'grooming_needs' => 3, 'shedding_level' => 4, 'intelligence' => 4,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => ['Hypertrophic cardiomyopathy', 'Hip dysplasia', 'Spinal muscular atrophy'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'One of the largest domestic breeds, with tufted ears, a shaggy water-resistant coat and a build suited to Maine\'s cold winters, its likely home of origin.',
                'temperament_summary' => 'Gentle giant: sociable, dog-like, good with families',
                'fun_fact' => 'The largest Maine Coon on record measured over four feet from nose to tail tip.',
            ],
            [
                'name' => 'Manx', 'slug' => 'manx', 'origin_country' => 'Isle of Man',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 3.5, 'weight_max_kg' => 5.5, 'coat_length' => 'short',
                'energy_level' => 3, 'affection_level' => 4, 'child_friendly' => 4, 'grooming_needs' => 2, 'shedding_level' => 3, 'intelligence' => 3,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => ['Manx syndrome, affecting the spine and nerves'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Best known for a natural genetic mutation that shortens or removes the tail entirely, isolated for centuries on the Isle of Man.',
                'temperament_summary' => 'Loyal, playful, strong hind legs make them good jumpers',
                'fun_fact' => 'Manx tail length varies naturally from a full stub to none at all, described by breeders as "rumpy", "stumpy" or "longy".',
            ],
            [
                'name' => 'Norwegian Forest Cat', 'slug' => 'norwegian-forest', 'origin_country' => 'Norway',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'large', 'weight_min_kg' => 4.0, 'weight_max_kg' => 9.0, 'coat_length' => 'long',
                'energy_level' => 3, 'affection_level' => 3, 'child_friendly' => 4, 'grooming_needs' => 3, 'shedding_level' => 4, 'intelligence' => 3,
                'lifespan_min' => 14, 'lifespan_max' => 16, 'health_watch' => ['Glycogen storage disease type IV', 'Hypertrophic cardiomyopathy'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A large, sturdy breed with a water-resistant double coat, shaped by centuries surviving Norwegian winters and appearing in Norse folklore.',
                'temperament_summary' => 'Independent but affectionate, a confident climber',
                'fun_fact' => 'This breed is thought to be the origin of the "skogkatt" in Norse mythology, a forest-dwelling cat said to be able to climb sheer rock.',
            ],
            [
                'name' => 'Oriental Shorthair', 'slug' => 'oriental-shorthair', 'origin_country' => 'United Kingdom',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'small', 'weight_min_kg' => 2.5, 'weight_max_kg' => 5.0, 'coat_length' => 'short',
                'energy_level' => 5, 'affection_level' => 5, 'child_friendly' => 3, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 5,
                'lifespan_min' => 12, 'lifespan_max' => 15, 'health_watch' => ['Progressive retinal atrophy', 'Dental disease'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'A Siamese body type bred in dozens of coat colors and patterns, sharing the same slender build and vocal, attention-seeking personality.',
                'temperament_summary' => 'Vocal, demanding of attention, bonds intensely with owners',
                'fun_fact' => 'Oriental Shorthairs come in more recognized colors and patterns than almost any other pedigreed breed.',
            ],
            [
                'name' => 'Persian', 'slug' => 'persian', 'origin_country' => 'Iran',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 3.0, 'weight_max_kg' => 5.5, 'coat_length' => 'long',
                'energy_level' => 1, 'affection_level' => 4, 'child_friendly' => 3, 'grooming_needs' => 5, 'shedding_level' => 5, 'intelligence' => 2,
                'lifespan_min' => 12, 'lifespan_max' => 17, 'health_watch' => ['Polycystic kidney disease', 'Flat-faced breathing difficulty'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'One of the oldest known breeds, with a flat face, thick long coat and calm temperament, first documented in the 1600s.',
                'temperament_summary' => 'Placid, dignified, prefers a calm household',
                'fun_fact' => 'Persians were reportedly kept by European nobility as early as the 17th century, brought west along trade routes from Persia.',
            ],
            [
                'name' => 'Ragamuffin', 'slug' => 'ragamuffin', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => false,
                'size_category' => 'large', 'weight_min_kg' => 4.5, 'weight_max_kg' => 9.0, 'coat_length' => 'medium',
                'energy_level' => 2, 'affection_level' => 5, 'child_friendly' => 5, 'grooming_needs' => 3, 'shedding_level' => 3, 'intelligence' => 3,
                'lifespan_min' => 12, 'lifespan_max' => 16, 'health_watch' => ['Hypertrophic cardiomyopathy', 'Polycystic kidney disease'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A close relative of the Ragdoll developed separately in the 1990s, sharing the same relaxed nature in a wider range of colors and patterns.',
                'temperament_summary' => 'Docile, floppy when held, very tolerant',
                'fun_fact' => 'Ragamuffins are known to go limp when picked up, much like their Ragdoll relatives, a trait breeders call "flopping".',
            ],
            [
                'name' => 'Ragdoll', 'slug' => 'ragdoll', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'large', 'weight_min_kg' => 4.5, 'weight_max_kg' => 9.0, 'coat_length' => 'medium',
                'energy_level' => 2, 'affection_level' => 5, 'child_friendly' => 5, 'grooming_needs' => 3, 'shedding_level' => 3, 'intelligence' => 3,
                'lifespan_min' => 12, 'lifespan_max' => 17, 'health_watch' => ['Hypertrophic cardiomyopathy'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A large, color-point breed developed in California in the 1960s, famous for going limp and relaxed when picked up.',
                'temperament_summary' => 'Docile, affectionate, follows owners around calmly',
                'fun_fact' => 'The name comes directly from the breed\'s tendency to go floppy, like a ragdoll toy, when held.',
            ],
            [
                'name' => 'Russian Blue', 'slug' => 'russian-blue', 'origin_country' => 'Russia',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 3.0, 'weight_max_kg' => 5.5, 'coat_length' => 'short',
                'energy_level' => 3, 'affection_level' => 3, 'child_friendly' => 3, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 4,
                'lifespan_min' => 15, 'lifespan_max' => 20, 'health_watch' => null, 'hypoallergenic' => true,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A dense, silvery-blue double coat and green eyes mark this reserved breed, thought to originate from Arkhangelsk in northern Russia.',
                'temperament_summary' => 'Reserved with strangers, deeply loyal to their people',
                'fun_fact' => 'The Russian Blue is one of the breeds most often cited as producing less of the Fel d 1 protein behind most cat allergies, though no cat is truly non-allergenic.',
            ],
            [
                'name' => 'Savannah', 'slug' => 'savannah', 'origin_country' => 'United States',
                'registry_tica' => true, 'registry_cfa' => false, 'registry_fife' => false,
                'size_category' => 'large', 'weight_min_kg' => 5.5, 'weight_max_kg' => 11.0, 'coat_length' => 'short',
                'energy_level' => 5, 'affection_level' => 3, 'child_friendly' => 2, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 5,
                'lifespan_min' => 12, 'lifespan_max' => 20, 'health_watch' => ['Hypertrophic cardiomyopathy'], 'hypoallergenic' => false,
                'good_for_apartments' => false, 'good_for_beginners' => false,
                'description' => 'A cross between a domestic cat and the African serval, producing a tall, long-legged cat; earlier generations (F1, F2) stay closest to the wild parent in size and needs.',
                'temperament_summary' => 'Bold, highly active, needs an experienced owner',
                'fun_fact' => 'Savannahs are known for jumping remarkably high, clearing eight feet from a standing position in some documented cases.',
            ],
            [
                'name' => 'Scottish Fold', 'slug' => 'scottish-fold', 'origin_country' => 'United Kingdom',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => false,
                'size_category' => 'medium', 'weight_min_kg' => 2.7, 'weight_max_kg' => 6.0, 'coat_length' => 'short',
                'energy_level' => 2, 'affection_level' => 4, 'child_friendly' => 4, 'grooming_needs' => 2, 'shedding_level' => 3, 'intelligence' => 3,
                'lifespan_min' => 11, 'lifespan_max' => 15, 'health_watch' => ['Osteochondrodysplasia, a painful joint condition linked to the folded-ear gene'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'Named for the folded-forward ears caused by a natural genetic mutation first seen on a Scottish farm in 1961.',
                'temperament_summary' => 'Sweet-natured, adaptable, quiet voice',
                'fun_fact' => 'Kittens are born with straight ears; the fold, in cats that have the gene, only appears at around three to four weeks old.',
            ],
            [
                'name' => 'Siamese', 'slug' => 'siamese', 'origin_country' => 'Thailand',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 2.5, 'weight_max_kg' => 5.0, 'coat_length' => 'short',
                'energy_level' => 5, 'affection_level' => 5, 'child_friendly' => 3, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 5,
                'lifespan_min' => 15, 'lifespan_max' => 20, 'health_watch' => ['Progressive retinal atrophy', 'Asthma', 'Amyloidosis'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'One of the oldest and most recognizable Asian breeds, with a color-point coat, striking blue eyes and one of the most vocal personalities of any cat.',
                'temperament_summary' => 'Extremely vocal, intelligent, forms one-person bonds',
                'fun_fact' => 'Siamese cats were once kept exclusively by Thai royalty, believed to bring good fortune to their households.',
            ],
            [
                'name' => 'Siberian', 'slug' => 'siberian', 'origin_country' => 'Russia',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'large', 'weight_min_kg' => 4.0, 'weight_max_kg' => 9.0, 'coat_length' => 'long',
                'energy_level' => 3, 'affection_level' => 4, 'child_friendly' => 4, 'grooming_needs' => 3, 'shedding_level' => 3, 'intelligence' => 4,
                'lifespan_min' => 12, 'lifespan_max' => 18, 'health_watch' => ['Hypertrophic cardiomyopathy'], 'hypoallergenic' => true,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A hardy, triple-coated breed built for harsh Russian winters, first written about in Russian fairy tales centuries ago.',
                'temperament_summary' => 'Playful, dog-like, strong jumper',
                'fun_fact' => 'Siberians are one of the breeds most often recommended to allergy sufferers, testing lower on average for the Fel d 1 protein than most breeds.',
            ],
            [
                'name' => 'Sphynx', 'slug' => 'sphynx', 'origin_country' => 'Canada',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 3.0, 'weight_max_kg' => 5.5, 'coat_length' => 'hairless',
                'energy_level' => 4, 'affection_level' => 5, 'child_friendly' => 4, 'grooming_needs' => 4, 'shedding_level' => 1, 'intelligence' => 4,
                'lifespan_min' => 13, 'lifespan_max' => 15, 'health_watch' => ['Hypertrophic cardiomyopathy', 'Skin conditions'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => false,
                'description' => 'A hairless breed from a natural mutation first bred in Ontario in the 1960s. No fur to trap body oils means regular skin bathing, not brushing.',
                'temperament_summary' => 'Energetic, attention-loving, seeks out warmth',
                'fun_fact' => 'Without a fur coat to keep them warm, Sphynx cats often seek out sunny spots, warm laps or even climb under blankets to regulate their temperature.',
            ],
            [
                'name' => 'Tonkinese', 'slug' => 'tonkinese', 'origin_country' => 'Canada',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 2.5, 'weight_max_kg' => 5.5, 'coat_length' => 'short',
                'energy_level' => 4, 'affection_level' => 5, 'child_friendly' => 4, 'grooming_needs' => 1, 'shedding_level' => 2, 'intelligence' => 4,
                'lifespan_min' => 14, 'lifespan_max' => 18, 'health_watch' => ['Asthma', 'Gingivitis'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'A deliberate cross between the Burmese and Siamese, landing in between both parent breeds in build, coat and vocal volume.',
                'temperament_summary' => 'Sociable, playful, a little quieter than a Siamese',
                'fun_fact' => 'Because it is a cross of two breeds, Tonkinese kittens from the same litter can lean more Burmese or more Siamese in looks and voice.',
            ],
            [
                'name' => 'Turkish Angora', 'slug' => 'turkish-angora', 'origin_country' => 'Turkey',
                'registry_tica' => true, 'registry_cfa' => true, 'registry_fife' => true,
                'size_category' => 'medium', 'weight_min_kg' => 2.5, 'weight_max_kg' => 4.5, 'coat_length' => 'long',
                'energy_level' => 4, 'affection_level' => 4, 'child_friendly' => 3, 'grooming_needs' => 2, 'shedding_level' => 3, 'intelligence' => 4,
                'lifespan_min' => 12, 'lifespan_max' => 18, 'health_watch' => ['Deafness in white, blue-eyed cats', 'Ataxia'], 'hypoallergenic' => false,
                'good_for_apartments' => true, 'good_for_beginners' => true,
                'description' => 'One of the oldest natural breeds, originating around Ankara, Turkey, with a fine silky coat that mats less than most other long-haired cats.',
                'temperament_summary' => 'Intelligent, active, bonds closely with one or two people',
                'fun_fact' => 'Turkish Angoras are strongly associated with Turkey\'s national heritage; the Ankara Zoo has run a breeding program to preserve the pure white line.',
            ],
        ];
    }
}
