<?php

/*
|--------------------------------------------------------------------------
| Catalogue
|--------------------------------------------------------------------------
| The tools and food guides shown on the home page. Keeping them here means
| the markup is a loop rather than twenty near-identical blocks, and adding
| a tool is one array entry.
|
| Blog articles used to live here too, as a `posts` entry. They moved into
| the `posts` database table, alongside the rest of the blog CMS, so the
| admin can author them and the public site reads real data rather than a
| second, hand-maintained copy of it. See App\Models\Post.
|
| This moves into the database once entries are edited rather than authored.
| The shape below is deliberately the shape those tables will have.
*/

return [

    'tools' => [
        [
            'slug' => 'cat-pregnancy-calculator',
            'published_at' => '2026-08-17',
            'updated_at' => '2026-08-28',
            'url' => '/tools/cat-pregnancy-calculator',
            'title' => 'Cat Pregnancy Calculator',
            'blurb' => 'Work out your cat’s due date and follow the pregnancy week by week.',
            'image' => 'cat-pregnancy-calculator-kitten',
            'alt' => 'Newborn kitten curled up asleep',
        ],
        [
            'slug' => 'cat-age-calculator',
            'published_at' => '2026-08-18',
            'updated_at' => '2026-08-28',
            'url' => '/tools/cat-age-calculator',
            'title' => 'Cat Age Calculator',
            'blurb' => 'Turn your cat’s age into human years, using the life-stage curve vets actually use.',
            'image' => 'cat-age-calculator-senior-tabby-cat',
            'alt' => 'Cats at five life stages from kitten to senior',
        ],
        [
            'slug' => 'cat-calorie-calculator',
            'published_at' => '2026-08-21',
            'updated_at' => '2026-08-28',
            'url' => '/tools/cat-calorie-calculator',
            'title' => 'Cat Calorie Calculator',
            'blurb' => 'Work out how much to feed each day from weight, life stage, activity and body condition.',
            'image' => 'cat-calorie-calculator-cat-food-bowl',
            'alt' => 'Cat beside a bowl of dry food',
        ],
        [
            'slug' => 'cat-weight-checker',
            'published_at' => '2026-08-24',
            'updated_at' => '2026-08-28',
            'url' => '/tools/cat-weight-checker',
            'title' => 'Weight Checker',
            'blurb' => 'Score body condition, see an ideal weight range, and log weight over time.',
            'image' => 'cat-weight-checker-cat-on-scale',
            'alt' => 'Fluffy cat sitting on a digital pet scale',
        ],
        [
            'slug' => 'vaccination-tracker',
            'published_at' => '2026-08-21',
            'updated_at' => '2026-08-28',
            'url' => '/tools/cat-vaccination-tracker',
            'title' => 'Cat Vaccination Tracker',
            'blurb' => 'Build a shot schedule from your cat’s birth date and keep every booster on time.',
            'image' => 'cat-vaccination-tracker-vet-examination',
            'alt' => 'Veterinarian examining a calm tabby cat',
        ],
        [
            'slug' => 'cat-name-generator',
            'published_at' => '2026-08-27',
            'updated_at' => '2026-08-30',
            'url' => '/tools/cat-name-generator',
            'title' => 'Cat Name Generator',
            'blurb' => 'Filter by style, personality and breed for a name with a real meaning behind it.',
            'image' => 'cat-name-generator-cute-kitten',
            'alt' => 'Fluffy kitten beside a board of name ideas',
        ],
    ],

    /*
     | Tools with no page built yet. Deliberately not part of 'tools' above:
     | every nav item, count and "X free tools" stat on the site reads from
     | 'tools' alone, so a not-yet-built tool never shows up as a dead link
     | or a "coming soon" card anywhere. Move an entry back up once its page
     | exists, adding a 'url' the same way the live ones have one.
     */
    'tools_upcoming' => [
        [
            'slug' => 'cat-breed-quiz',
            'title' => 'Breed Quiz',
            'blurb' => 'Answer a few questions about coat, build and temperament to narrow down the breed.',
            'image' => 'cat-breed-quiz-multiple-cat-breeds',
            'alt' => 'Persian, Siamese and Maine Coon cats side by side',
        ],
    ],

    /*
     | verdict drives the badge color on each card: safe, caution or unsafe.
     | Showing the answer on the card itself is the point. Someone worried
     | about what their cat just ate gets it without a second click.
     */
    'foods' => [
        [
            'slug' => 'fruits',
            'published_at' => '2026-08-17',
            'updated_at' => '2026-08-28',
            'title' => 'Fruits',
            'question' => 'Can Cats Eat Fruit?',
            'answer' => 'Small amounts of melon, blueberries or apple flesh are fine. Never grapes or raisins.',
            'verdict' => 'caution',
            'note' => 'Some in small amounts',
            'image' => 'can-cats-eat-fruits-fresh-colorful-fruits',
            'alt' => 'Strawberries, blueberries, watermelon and apple beside a cat',
            'why' => "Cats are obligate carnivores, and that is a biological fact, not a dietary trend: they cannot synthesize taurine, arachidonic acid or vitamin A from plant sources the way an omnivore can, so a meat-based diet is a requirement, not a preference. Sweetness plays no part in that at all. Cats are one of the few mammal families known to carry a broken copy of Tas1r2, the gene that builds a sweet-taste receptor in most other mammals, most likely because a diet built entirely around hunting prey never rewarded a taste for sugar over millions of years. That is measurable, not folklore: offered a bowl of sugar water beside a bowl of plain water, a cat shows no preference for either, unlike almost any other mammal tested the same way. So when a cat does show interest in a piece of watermelon or cantaloupe, it is very likely reacting to the texture, temperature or moisture rather than the sweetness itself. None of that makes fruit dangerous the way onion or grapes are, but it also does not make fruit useful: it is mostly water, fiber and natural sugar, and none of those are things a cat's diet is short on. A bite here and there is a harmless novelty for most cats, not a food group worth building into a routine, and never a stand-in for the animal protein a cat's body actually runs on.",
            'guidance' => "For the fruits marked safe or caution below, a small amount, roughly a bite or two, not a serving, is the right ceiling, and that holds whether it is the first time or the fiftieth. Treats of any kind, fruit included, are generally kept to no more than about 10 percent of a cat's total daily calories, a rule of thumb used across pet nutrition guidance rather than something specific to fruit, and for an average indoor cat eating around 200 to 250 calories a day, that leaves very little room, closer to one or two small pieces of fruit than anything resembling a serving a person would eat. Frequency matters as much as amount: an occasional piece is a novelty, while fruit offered daily starts to displace the balanced, complete food actually doing the nutritional work, especially in a cat already managing weight or a condition like diabetes, where the extra natural sugar is worth discussing with a vet first rather than assuming small means harmless. Preparation matters just as much as the fruit itself. Plain is the only acceptable form: no sugar, syrup, chocolate, yogurt dip, or anything baked into a dessert, since those additions carry their own risks entirely separate from the fruit. Seeds, pits, rinds and leafy tops come off first, every time, not just for the fruits where that is called out explicitly below, since a cat does not read a safety table before deciding what to swallow whole. Grapes and raisins are the one hard exception in this entire category: they are linked to acute kidney injury in cats and dogs, the mechanism is still not fully understood, and there is no known safe amount, so they are treated as off-limits entirely rather than a moderation food.",
            'introduce' => "Introduce any new fruit the same cautious way, one piece at a time. Cut a small amount into a size a cat can eat without gulping it whole, since choking risk goes up with bigger pieces, remove any seeds, pits, rind or leafy tops first, and offer it plain, nothing added for a person's dessert doubles as a genuine risk for a cat. Wait roughly 24 hours before offering anything else new, watching for vomiting, diarrhea, or a cat simply refusing their regular food, any of which is a reason to stop and not offer that fruit again. A cat that shows no interest at all is not being fussy, it is being a cat: with no working sweet-taste receptor, there is no biological pull toward fruit the way there might be toward a piece of chicken, so plenty of cats simply pass on it entirely, and that is a normal, healthy response, not something to coax past.",
            'items' => [
                ['name' => 'Watermelon (seedless flesh)', 'verdict' => 'safe', 'note' => 'Over 90% water and low in calories. Remove seeds and rind first, both a choking and blockage risk rather than a toxicity one.'],
                ['name' => 'Cantaloupe & honeydew melon', 'verdict' => 'safe', 'note' => 'Same reasoning as watermelon. Remove the rind and any seeds before offering.'],
                ['name' => 'Strawberries', 'verdict' => 'safe', 'note' => 'A small piece is fine. Remove the leafy top first.'],
                ['name' => 'Blueberries', 'verdict' => 'safe', 'note' => 'A common low-calorie treat choice, whole or lightly mashed.'],
                ['name' => 'Banana', 'verdict' => 'caution', 'note' => 'Higher in natural sugar and carbohydrate than most fruit here, so a thin slice now and then, not a daily habit.'],
                ['name' => 'Apple (flesh only)', 'verdict' => 'caution', 'note' => 'Remove seeds and the core. Apple seeds contain trace cyanogenic compounds.'],
                ['name' => 'Pear (flesh only)', 'verdict' => 'caution', 'note' => 'Same seed and core caution as apple.'],
                ['name' => 'Mango (flesh only)', 'verdict' => 'caution', 'note' => 'Remove the pit and skin. The pit is a genuine obstruction risk on its own, separate from any toxicity concern.'],
                ['name' => 'Pineapple', 'verdict' => 'caution', 'note' => 'High in natural sugar and acidity. A small piece of flesh only, skin and core removed.'],
                ['name' => 'Peaches, plums & apricots (flesh only)', 'verdict' => 'caution', 'note' => 'Remove the pit entirely. Stone-fruit pits carry the same cyanogenic-compound risk as apple seeds, at a higher concentration.'],
                ['name' => 'Cherries (flesh only)', 'verdict' => 'caution', 'note' => 'Same pit and stem risk as other stone fruit. The flesh alone is not the main concern here.'],
                ['name' => 'Citrus (orange, lemon, lime)', 'verdict' => 'caution', 'note' => 'The flesh is not especially dangerous, but the peel, pith and seeds can irritate skin and the gut, and most cats avoid the scent on their own.'],
                ['name' => 'Coconut (fresh, plain)', 'verdict' => 'caution', 'note' => 'Small amounts are usually tolerated. The fat content can trigger diarrhea, so skip flavored or desiccated coconut products.'],
                ['name' => 'Avocado', 'verdict' => 'caution', 'note' => 'Often listed as toxic to pets due to persin, a compound cats appear to tolerate better than birds do. The pit is a serious choking and blockage hazard regardless, and it offers a cat no nutritional upside worth the risk.'],
                ['name' => 'Grapes & raisins', 'verdict' => 'unsafe', 'note' => 'Linked to acute kidney injury in cats and dogs. No known safe amount, even a single grape.'],
            ],
            'avoid' => [
                'Grapes and raisins, in any amount or form, fresh, dried, or baked into something else, linked to acute kidney injury with no known safe dose.',
                'Cherry, peach, plum and apricot pits and stems, which carry cyanogenic compounds at a concentration high enough to matter, on top of being a choking and blockage risk on their own.',
                'Apple and pear seeds and cores, for the same cyanogenic-compound reason, in a smaller but still real amount.',
                'Citrus peel, pith and seeds, which contain compounds that can irritate skin and the digestive tract.',
                'Any fruit prepared with added sugar, chocolate, xylitol or alcohol: a fruit salad, a slice of pie, or a chocolate-dipped strawberry is a different risk profile entirely from the plain fruit.',
                'Avocado pit and skin specifically, a blockage hazard regardless of how the flesh itself is judged.',
            ],
            'watch_for' => [
                'Vomiting, diarrhea or reduced appetite after eating any new fruit',
                'Any amount of grape or raisin eaten, even a small piece, warrants a call to a vet',
                'Lethargy or decreased urination in the day or two after eating grapes or raisins',
                'Gagging, drooling or repeated swallowing shortly after eating a fruit with a pit or seed, a possible sign it is stuck rather than swallowed cleanly',
            ],
            'faq' => [
                ['q' => 'Can cats eat grapes?', 'a' => 'No. Grapes and raisins are linked to acute kidney injury in cats, the exact toxic mechanism is still not understood, and there is no dose considered safe, even a single grape. If a cat eats any amount of grape or raisin, call a vet rather than waiting to see if symptoms appear.'],
                ['q' => 'Can cats eat watermelon?', 'a' => 'Yes, in small amounts. Watermelon flesh is over 90 percent water and low in calories, which makes it one of the gentler fruits to offer, but the seeds and rind should come off first since both are a choking and blockage risk rather than a toxicity one.'],
                ['q' => 'Can cats eat strawberries?', 'a' => "Yes, a small piece is fine. Strawberries carry natural sugar and no nutrition a cat's diet needs, so treat them as an occasional novelty rather than a regular treat, and remove the leafy top before offering any."],
                ['q' => 'Can cats eat bananas?', 'a' => 'Yes, in small amounts. Banana is higher in natural sugar and carbohydrate than most fruit on this page, so a thin slice now and then is plenty.'],
                ['q' => 'Is any fruit actually good for a cat, nutritionally?', 'a' => "Not in a way that matters. Fruit is mostly water, fiber and natural sugar, none of which fills a gap in a cat's diet, since cats get everything they need from animal protein and fat. A bite of fruit is a texture and novelty experience for a cat, not a nutritional contribution."],
                ['q' => 'How much fruit can I give my cat in one sitting?', 'a' => "A bite or two, not a bowlful. Treats of any kind, fruit included, are generally kept to no more than about 10 percent of a cat's daily calories, and for an average cat that is a small amount, closer to one or two small pieces than a serving."],
            ],
            'deep_dives' => [
                ['label' => 'Can Cats Eat Bananas?', 'slug' => 'can-cats-eat-bananas'],
            ],
        ],
        [
            'slug' => 'vegetables',
            'published_at' => '2026-08-17',
            'updated_at' => '2026-08-30',
            'title' => 'Vegetables',
            'question' => 'Can Cats Eat Vegetables?',
            'answer' => 'Plain cooked carrot, broccoli or pumpkin in small amounts. Skip onion, garlic and leek entirely.',
            'verdict' => 'caution',
            'note' => 'Cooked and plain only',
            'image' => 'can-cats-eat-vegetables-fresh-greens',
            'alt' => 'Broccoli, cucumber, spinach and carrots beside a cat',
            'why' => "Cats are obligate carnivores, and that shapes how their whole digestive system is built, not just what they crave. A cat's gut is short relative to its body, its intestinal surface area is a fraction of an omnivore's, and it produces very little amylase, the enzyme that breaks starch down into usable sugar, because none of that was ever needed to hunt and process prey. Vegetables are not built the way meat is. Their cell walls are made of cellulose, a fiber a cat's gut cannot break down on its own, which is why a raw vegetable tends to pass through mostly intact and can cause more gas or looser stool than the same vegetable cooked. Cooking ruptures those cell walls mechanically, and that is the real reason a plain cooked vegetable sits easier than a raw one, not any change in what nutrients it offers. None of this makes vegetables dangerous as a category. Unlike onion or garlic, a plain cooked vegetable carries no toxin at all for most of the items on this page, and the concern is almost always digestive tolerance or a specific prep mistake, not a poison. But it also does not make vegetables useful. A cat gets everything its body needs, taurine, arachidonic acid, vitamin A, from animal tissue, and a vegetable fills none of those gaps no matter how it is cooked. A spoonful of plain carrot or pumpkin is a fiber and texture addition a cat's gut can tolerate, not a nutritional contribution, and never a stand-in for the meat its metabolism actually runs on.",
            'guidance' => "For the vegetables marked safe or caution below, plain and cooked is the default: steamed or boiled, nothing added, no butter, oil, salt or seasoning, cut into pieces small enough that a cat swallows them cleanly rather than gulping down a chunk whole. A few, carrot, green beans, peas and corn kernels off the cob among them, are tolerated raw in small amounts, but cooking is the safer default across the board, since it softens the cellulose a cat's gut cannot break down and removes surface bacteria raw produce can carry. Treat vegetables the way you would any other treat: roughly a spoonful or two per feeding, a few times a week rather than daily, counted toward the general rule of keeping treats of any kind under about 10 percent of a cat's total daily calories, alongside a complete, balanced food doing the actual nutritional work. Spinach deserves its own note. It is fine occasionally for most cats, but it is relatively high in oxalates, and a cat with any history of urinary crystals or bladder stones is better off skipping it entirely, since oxalates are a real contributing factor behind the crystal and stone formation covered in more depth in our guide to <a href=\"/blog/cat-uti-symptoms\" class=\"font-semibold text-primary underline decoration-line-strong underline-offset-4\">UTI symptoms in cats</a>. The one category with no moderation version at all is the allium family, covered in full on our <a href=\"/food-guides/toxic-foods\" class=\"font-semibold text-primary underline decoration-line-strong underline-offset-4\">toxic foods guide</a>: onion, garlic, leek, chives and shallots. Raw, cooked, powdered, or hidden in a broth or seasoning blend, every form damages a cat's red blood cells and can cause a serious anemia, even from an amount that looks trivially small, with no safe threshold to build a habit around. That family is treated as an automatic no on this page, never a judgment call.",
            'introduce' => "Introduce any new vegetable the same cautious way, one at a time. Cook a small amount plain, cut it into pieces sized for a cat's mouth rather than a person's bite, and offer just a taste, not a full spoonful, the first time. Wait roughly 24 hours before trying anything else new, watching for vomiting, diarrhea, gas, or a cat that goes off its regular food, any of which is a reason to stop and not offer that vegetable again. No reaction after a day is a reasonable sign of tolerance, though that only covers digestive upset, not the allium family, where there is no safe amount to work up to no matter how well a cat handles it. Overall daily portion size matters as much as any single new item does: a vegetable that sits fine on its own can still push a cat past its daily calorie total if it is layered on top of full meals instead of counted against them, and our <a href=\"/tools/cat-calorie-calculator\" class=\"font-semibold text-primary underline decoration-line-strong underline-offset-4\">calorie calculator</a> is the fastest way to see what that total is for a cat's weight and activity level before adding extras. A cat that shows no interest at all is not being fussy, it simply is not built to crave plant matter, and that is a normal response, not something to coax past.",
            'items' => [
                ['name' => 'Carrot (cooked)', 'verdict' => 'safe', 'note' => "Steamed or boiled until fork-soft, no seasoning. Raw carrot is a genuine choking and obstruction risk, since a cat's shearing teeth tend to bite off chunks rather than grind them down. Limit to about half a teaspoon, mashed or diced, once or twice a week."],
                ['name' => 'Broccoli (cooked)', 'verdict' => 'caution', 'note' => 'Steamed or boiled plain, stems removed, florets cut small. Contains glucosinolates that turn into gas-causing irritants once cut or cooked, so a thumb-sized portion, once or twice a week, is the ceiling. More than that can bring on gas or loose stool.'],
                ['name' => 'Cauliflower (cooked)', 'verdict' => 'caution', 'note' => 'Cooked only, plain, in small florets; raw cauliflower is harder to digest. Ferments in the gut and can cause gas or bloating at more than a floret or two, from an indigestible sugar plus the same sulfur compounds broccoli carries.'],
                ['name' => 'Green beans (cooked)', 'verdict' => 'safe', 'note' => 'Fresh, frozen or cooked, cut into bite-sized pieces, a low-calorie snack vets often recommend. Skip seasoned or canned holiday-style green bean blends, which can carry onion or garlic powder, a real hazard the bean itself does not carry at all.'],
                ['name' => 'Peas', 'verdict' => 'safe', 'note' => 'Fresh or frozen only, boiled soft and mashed rather than left whole, since intact skins are an unnecessary choking risk. Keep it under a tablespoon a week, and skip it entirely for a cat with diagnosed kidney disease, given its purine content.'],
                ['name' => 'Pumpkin (plain, cooked or canned)', 'verdict' => 'safe', 'note' => 'Plain canned pumpkin, never pie filling, which is spiked with sugar and spices like nutmeg. Its soluble fiber firms up loose stool or eases mild constipation either way. A teaspoon or two mixed into a meal is the usual vet-recommended dose.'],
                ['name' => 'Cucumber', 'verdict' => 'caution', 'note' => 'Peeled, washed, and cut into small pieces, since the skin is fibrous and harder to digest. About 95 percent water, so more than a slice or two at a time tends toward loose stool. Never pickled or brined, which adds sodium and sometimes onion.'],
                ['name' => 'Zucchini (cooked)', 'verdict' => 'caution', 'note' => "Steamed or baked plain and diced small; raw zucchini is not toxic but harder on a cat's gut. Skip any zucchini or squash that tastes bitter, homegrown fruit included, a sign of cucurbitacin, a natural toxin that heat does not destroy."],
                ['name' => 'Celery', 'verdict' => 'caution', 'note' => 'Wash and strip the tough outer strings before cutting into small plain pieces; the stringy fiber is a real choking risk for a cat that tends to gulp rather than chew. Skip the ranch or peanut-butter dip celery is usually served with.'],
                ['name' => 'Sweet potato (cooked)', 'verdict' => 'safe', 'note' => 'Boiled, steamed or baked plain with the skin removed; raw is a starchy choking and digestion risk, not a toxic one. Mash or cube it small, and keep it to about half a teaspoon at most, once or twice a week.'],
                ['name' => 'Potato (cooked, no green skin)', 'verdict' => 'caution', 'note' => 'Fully cooked with every trace of skin removed, not just green or sprouted patches, since ordinary skin still carries solanine and cooking only cuts it by roughly a third. Green, sprouted, or raw potato is a genuine poisoning risk on its own.'],
                ['name' => 'Corn kernels (off the cob)', 'verdict' => 'safe', 'note' => 'Boiled or steamed plain, off the cob; the kernels themselves carry no toxin. The cob is the real hazard, a fibrous, indigestible cylinder that can lodge in the intestine, so it is never something to let a cat chew on directly.'],
                ['name' => 'Tomato (ripe flesh only)', 'verdict' => 'caution', 'note' => 'Only fully ripe, all-red flesh, no stem, leaf, vine, or green fruit, which contain solanine and tomatine at levels that can cause drooling and stomach upset. Skip sauce, ketchup, and canned tomato products, which usually add onion or garlic too.'],
                ['name' => 'Mushrooms (plain, store-bought only)', 'verdict' => 'caution', 'note' => 'Only grocery-store button, cremini, or portobello mushrooms, cooked plain, count. Never a wild or lawn mushroom: toxic and harmless species look alike to a non-expert, and some cause liver or kidney damage after a deceptive symptom-free window.'],
                ['name' => 'Spinach', 'verdict' => 'caution', 'note' => 'Fine occasionally in a small amount, briefly boiled with the water discarded, which cuts its oxalate content substantially. Best skipped by a cat with any history of urinary crystals or bladder stones, where oxalates are a genuine contributing factor.'],
                ['name' => 'Brussels sprouts', 'verdict' => 'caution', 'note' => 'Steamed or boiled until fork-soft, cut small; never raw, which can carry soil bacteria and is harder to digest. About half to one small cooked sprout, once or twice a week, is enough to avoid gas or loose stool afterward.'],
                ['name' => 'Onion, garlic, leek, chives & shallots', 'verdict' => 'unsafe', 'note' => "Every form, raw, cooked, powdered, or in a broth or bouillon, damages a cat's red blood cells and can cause a serious anemia. No known safe amount in any quantity, and powdered forms are actually more concentrated than the fresh vegetable."],
            ],
            'avoid' => [
                "Onion, garlic, leek, chives and shallots, in any form, raw, cooked, dehydrated or powdered in a broth, gravy, or seasoning blend: organosulfur compounds in every member of this family damage a cat's red blood cells and can cause a serious anemia, with no dose considered safe and powdered forms actually more concentrated than the fresh vegetable.",
                'Corn on the cob: the kernels are harmless, but the fibrous, indigestible cob itself can lodge in the intestine and often has to be removed surgically.',
                'Green or sprouted potato, and potato skin in any form, raw or cooked: both carry solanine at a level cooking does not fully neutralize, and can cause vomiting, drooling and, in serious cases, tremors.',
                'Unripe, green tomato and any tomato stem, leaf or vine: these carry the same solanine-family toxin as green potato, at levels the ripe red flesh does not.',
                'Wild, foraged or lawn mushrooms, including anything a cat might find growing in the yard: toxic and harmless species are frequently impossible to tell apart, and the most dangerous toxins cause organ damage after a deceptive symptom-free period.',
                'Pickled, brined, salted, buttered or seasoned vegetables of any kind, and any dip served alongside them, ranch, cheese sauce or seasoned oil: the sodium, fat and often onion or garlic powder are a separate, real hazard from the plain vegetable itself.',
                'Bitter-tasting squash or zucchini, especially homegrown or garden-grown fruit: bitterness signals cucurbitacin, a natural plant toxin that heat does not destroy and that causes vomiting and abdominal pain in cats.',
            ],
            'watch_for' => [
                'Vomiting, diarrhea or gas within a few hours of a new vegetable, more likely from a raw or cruciferous one than a cooked, plain one',
                'Pale gums, weakness, a fast heart rate or dark urine in the day or two after any onion, garlic, leek, chives or shallot exposure, signs of the anemia this family causes',
                'Straining to urinate, blood in the litter box, or frequent trips to the box in a cat with a history of urinary crystals after spinach or another oxalate-heavy vegetable',
                'Gagging, drooling or repeated swallowing after a fibrous vegetable like celery or a piece of corn cob, a possible sign something is stuck rather than swallowed cleanly',
            ],
            'faq' => [
                ['q' => 'Can cats eat onions or garlic?', 'a' => "No. Onion, garlic, leek, chives and shallots, in any form, raw, cooked or powdered, damage a cat's red blood cells and can cause a serious anemia. There is no known safe amount, and powdered or dehydrated forms are actually more concentrated than the fresh vegetable. If a cat eats any amount, call a vet rather than waiting for symptoms."],
                ['q' => 'Can cats eat broccoli?', 'a' => 'Yes, in small amounts, cooked plain. Broccoli is not toxic to cats, but it contains compounds that turn into gas-causing irritants once it is cut or cooked, so a thumb-sized portion once or twice a week is plenty. Remove the stems first, both a digestion and a choking concern.'],
                ['q' => 'Can cats eat carrots?', 'a' => "Yes, cooked and cut small. Raw carrot is hard, and a cat's shearing teeth tend to bite off chunks rather than grind them down, which makes it a real choking risk. Steamed or boiled until soft, then mashed or diced, carrot is a low-calorie, guilt-free treat in small amounts."],
                ['q' => 'Can cats eat tomatoes?', 'a' => 'Only fully ripe, red flesh, and only a small amount. Tomato is a nightshade, and its stem, leaves, vine and any green, unripe fruit carry solanine and tomatine at levels that can cause drooling and stomach upset. Skip sauce and ketchup entirely, both usually contain onion or garlic.'],
                ['q' => 'Can cats eat potatoes?', 'a' => 'Only fully cooked, fully peeled potato flesh, with no trace of skin. Ordinary potato skin still carries solanine, and cooking only cuts it by around a third, so the skin has to come off entirely. Green, sprouted, or raw potato is a genuine poisoning risk and should never be fed.'],
                ['q' => 'Are vegetables good for cats nutritionally?', 'a' => "Not in a way that fills a real gap. Cats get taurine, arachidonic acid and vitamin A from animal tissue, and no vegetable supplies those. A spoonful of plain cooked vegetable adds fiber and variety a cat's gut can tolerate, not a nutritional contribution its diet is actually missing."],
                ['q' => 'How much vegetable can I give my cat?', 'a' => "A spoonful or two at most, a few times a week, not daily. Treats of any kind, vegetables included, are generally kept under about 10 percent of a cat's total daily calories, with a complete, balanced food doing the rest of the nutritional work day to day."],
            ],
            'deep_dives' => [
                ['label' => 'Can Cats Eat Broccoli?', 'slug' => 'can-cats-eat-broccoli'],
            ],
        ],
        [
            'slug' => 'meat-and-seafood',
            'published_at' => '2026-08-17',
            'updated_at' => '2026-08-25',
            'title' => 'Meat & Seafood',
            'question' => 'Can Cats Eat Meat and Fish?',
            'answer' => 'Yes. Plain cooked chicken, turkey or fish, boneless and without salt, oil or seasoning.',
            'verdict' => 'safe',
            'note' => 'Cooked, unseasoned',
            'image' => 'can-cats-eat-meat-seafood-chicken-fish',
            'alt' => 'Chicken, salmon and tuna beside a cat',
            'why' => 'Meat is the one category here a cat\'s body is actually built to run on. Cats need taurine, an amino acid found almost exclusively in animal tissue, and plain cooked meat or fish is close to what already makes up a complete commercial cat food. This is the safest category on this page by a wide margin, with a short, specific list of things to get right.',
            'guidance' => 'Plain cooked chicken, turkey, beef, lean pork or fish, with all bones removed and no salt, oil, butter or seasoning, especially no onion or garlic powder, is a good addition or occasional topper to a normal diet. Cooking removes the bacterial risk raw meat carries, including salmonella and campylobacter, which can make a cat unwell and can also spread to people handling the food and litter tray afterward. Fish specifically is best kept occasional rather than a staple: raw fish contains an enzyme called thiaminase that breaks down vitamin B1, and a diet too heavy in fish, cooked or raw, has been linked to steatitis, a painful inflammation of body fat from too much unsaturated fat without enough vitamin E to balance it. Cooked bones are never safe: they turn brittle and can splinter and injure the throat or gut on the way through.',
            'watch_for' => [
                'Vomiting or diarrhea after raw meat or fish specifically',
                'Difficulty swallowing, drooling or pawing at the mouth after any bone-in meat',
                'Repeated fatty extras (skin, drippings) are a recognized risk factor for pancreatitis',
            ],
            'deep_dives' => [
                ['label' => 'Can Cats Eat Chicken?', 'slug' => 'can-cats-eat-chicken'],
                ['label' => 'Can Cats Eat Tuna?', 'slug' => 'can-cats-eat-tuna'],
            ],
        ],
        [
            'slug' => 'dairy-and-eggs',
            'published_at' => '2026-08-17',
            'updated_at' => '2026-08-25',
            'title' => 'Dairy & Eggs',
            'question' => 'Can Cats Eat Dairy and Eggs?',
            'answer' => 'Cooked egg is fine. Most adult cats are lactose intolerant, so milk and cheese cause upset.',
            'verdict' => 'caution',
            'note' => 'Most cats are lactose intolerant',
            'image' => 'can-cats-eat-dairy-eggs-milk-cheese',
            'alt' => 'Eggs, milk and cheese beside a cat',
            'why' => 'Kittens produce plenty of lactase, the enzyme that digests milk sugar, because they need it to nurse. Most cats lose much of that ability once weaned, the same way many adult humans do, so cow\'s milk sits in an adult cat\'s gut largely undigested and pulls water into the intestine, which is what causes the diarrhea people often report after giving a cat a saucer of milk.',
            'guidance' => 'Plain cooked egg, scrambled or hard-boiled with nothing added, is a genuinely good source of protein in small amounts. Milk and cream are best skipped for any adult cat with unknown tolerance; a small amount of hard cheese or plain yogurt, which carry less lactose than milk, is tolerated by some cats without issue. Raw eggs carry a real salmonella risk and also contain avidin, a protein that binds biotin and can interfere with its absorption over time, so eggs are always better cooked than raw.',
            'watch_for' => [
                'Diarrhea or soft stool within a few hours of milk, cream or a large amount of dairy',
                'Vomiting after raw egg specifically',
                'Excessive gas or bloating after cheese',
            ],
            'deep_dives' => [
                ['label' => 'Can Cats Eat Eggs?', 'slug' => 'can-cats-eat-eggs'],
                ['label' => 'Can Cats Eat Cheese?', 'slug' => 'can-cats-eat-cheese'],
            ],
        ],
        [
            'slug' => 'toxic-foods',
            'published_at' => '2026-08-17',
            'updated_at' => '2026-08-25',
            'title' => 'Toxic Foods',
            'question' => 'What Foods Are Toxic to Cats?',
            'answer' => 'Onion, garlic, chocolate, grapes, raisins, alcohol and xylitol. Call a vet if any is eaten.',
            'verdict' => 'unsafe',
            'note' => 'Never. Call a vet',
            'image' => 'toxic-foods-cats-must-avoid-dangerous',
            'alt' => 'Chocolate, garlic, onion and grapes marked as dangerous',
            'why' => 'This list covers the foods that are dangerous in genuinely small amounts, not just unhealthy in excess: a bite, not a bowlful, is enough to matter for several of these. Cats are also smaller than most dogs, which means the same amount of a toxic food does more damage per pound of body weight, and cats metabolize some of these compounds, caffeine and theobromine in particular, more slowly than people do.',
            'guidance' => 'Onion, garlic, leek and chives, in any form, cooked, raw or powdered, damage red blood cells and can cause anemia. Chocolate contains theobromine and caffeine, both toxic to a cat\'s heart and nervous system, with darker and baking chocolate far more concentrated than milk chocolate. Grapes and raisins are linked to acute kidney injury by a mechanism still not fully understood, with no known safe amount. Alcohol affects a cat\'s small body fast and can be dangerous in amounts that would do nothing to a person. Xylitol, an artificial sweetener increasingly common in sugar-free gum, peanut butter and baked goods, is established as dangerous in dogs and treated with the same caution in cats. If you know or suspect your cat ate any of these, call your vet or an animal poison control line immediately rather than waiting to see if symptoms appear, and do not induce vomiting unless a vet specifically tells you to.',
            'watch_for' => [
                'Vomiting, diarrhea, weakness or pale gums, common early signs across most of these',
                'Rapid breathing, tremors or an elevated heart rate after chocolate, caffeine or alcohol',
                'Lethargy or reduced urination in the day or two after grapes or raisins',
                'Any known ingestion, even without symptoms yet, is worth an immediate call, not a wait-and-see',
            ],
        ],
        [
            'slug' => 'grains-and-seeds',
            'published_at' => '2026-08-17',
            'updated_at' => '2026-08-25',
            'title' => 'Grains & Seeds',
            'question' => 'Can Cats Eat Grains and Seeds?',
            'answer' => 'Small amounts of cooked rice or oats are harmless, but cats gain nothing nutritionally from them.',
            'verdict' => 'caution',
            'note' => 'Cooked, in tiny amounts',
            'image' => 'can-cats-eat-grains-seeds-rice-oats',
            'alt' => 'Rice, oats, quinoa and seeds in bowls beside a cat',
            'why' => 'Cats have no biological requirement for carbohydrate: unlike people or dogs, they do not need grains as an energy source, and a diet built around meat already meets their needs without them. That does not make grains dangerous, just unnecessary, which is a different thing from the foods elsewhere on this page.',
            'guidance' => 'A small amount of plain cooked rice or oats, with nothing added, is harmless for most cats and sometimes used to settle an upset stomach. Some cats do show a grain sensitivity, with itchy skin or digestive upset as the main signs, though true grain allergy is less common in cats than marketing around grain-free food often implies. Seeds are best kept plain and unsalted, in small quantities; the concern with seasoned or salted seeds is the salt and any onion or garlic seasoning mixed in, not the seed itself.',
            'watch_for' => [
                'Itchy skin, ear infections or soft stool that shows up consistently after a specific grain',
                'Bloating or gas after a larger-than-usual portion',
            ],
            'deep_dives' => [
                ['label' => 'Can Cats Eat Bread?', 'slug' => 'can-cats-eat-bread'],
                ['label' => 'Can Cats Eat Chickpeas?', 'slug' => 'can-cats-eat-chickpeas'],
            ],
        ],
        [
            'slug' => 'sweets',
            'published_at' => '2026-08-17',
            'updated_at' => '2026-08-25',
            'title' => 'Sweets',
            'question' => 'Can Cats Eat Sweets?',
            'answer' => 'No. Cats cannot taste sweetness, and chocolate and xylitol are outright poisonous.',
            'verdict' => 'unsafe',
            'note' => 'No nutritional value',
            'image' => 'can-cats-eat-sweets-desserts-unsafe',
            'alt' => 'Chocolate cake, sweets and ice cream beside a cat',
            'why' => 'Cats are missing a functional version of the gene for the sweet taste receptor, which means they genuinely cannot taste sugar the way people, dogs, or most other mammals do. A cat begging at the table while you eat dessert is responding to fat, texture or your attention, not a craving for sweetness, since that sense does not exist for them.',
            'guidance' => 'There is no safe serving size to give here, because sweets as a category are built almost entirely from things that are actively bad for a cat rather than just empty calories: chocolate and xylitol both turn up constantly in desserts and are genuinely dangerous, and the high sugar and fat content of the rest offers a cat nothing while raising the risk of obesity, dental disease and pancreatitis over time. The honest answer is to keep sweets away from cats entirely rather than manage a moderate amount.',
            'watch_for' => [
                'Vomiting, diarrhea or lethargy after any sweet treat, especially one containing chocolate',
                'Any suspected xylitol exposure is an emergency: call a vet immediately',
            ],
        ],
        [
            'slug' => 'junk-food',
            'published_at' => '2026-08-17',
            'updated_at' => '2026-08-30',
            'title' => 'Junk & Fast Food',
            'question' => 'Can Cats Eat Junk Food or Fast Food?',
            'answer' => 'No. Fries, chips, burgers and pizza carry far more salt and fat than a cat\'s body can process, and the fat load is a genuine pancreatitis trigger.',
            'meta_description' => 'French fries, pizza and fast-food burgers carry more salt, fat and hidden onion than a cat\'s body can handle. See the full item-by-item breakdown.',
            'verdict' => 'unsafe',
            'note' => 'Salt, fat and hidden onion',
            'image' => 'can-cats-eat-junk-food-fast-food',
            'alt' => 'Fries, burger and pizza beside a cat',
            'why' => 'Fast food and packaged snacks are formulated for a much larger animal with different nutrition needs, and several of the ingredients that make them taste good to a person carry a real, checkable risk for a cat. Onion and garlic powder are standard in burger seasoning, breading, ketchup and barbecue sauce, and the powdered form is not a smaller dose than the fresh vegetable, it is a more concentrated one, since dehydrating onion or garlic removes the water and leaves the toxic compound behind. Salt is a separate risk with its own threshold: symptoms can start around half a gram of salt per kilogram of body weight, so a typical 9-pound cat can reach that point with roughly 2 grams, well under a teaspoon, which a heavily salted portion of fries or chips can approach faster than it looks. Fat is the third mechanism, and the one with the most serious downside: a sudden greasy meal is a real trigger for pancreatitis in cats, an inflamed, painful pancreas, not just an upset stomach. Caffeine in soda and theobromine in chocolate are different again, both stimulants a cat\'s body clears far more slowly than a person\'s does.',
            'guidance' => 'A single dropped fry, a lick of a plain bun or a corner of a plain cheese-only crust is not an emergency for most cats, and the table below breaks down which specific item carries which risk. What warrants a call to a vet is anything seasoned: a bite of a fully dressed burger with sauce, a ketchup-dipped fry, a flavored chip, a slice of pepperoni pizza, or fried chicken with the breading still on, since onion and garlic powder are standard in all of those and there is no established safe dose for a cat. Soda and any candy or dessert containing chocolate get the same treatment regardless of amount, since caffeine and theobromine are toxic on their own terms and a cat\'s body clears them slowly. If a cat gets into any of those, do not wait to see if it seems fine: hemolytic anemia from onion or garlic can take three to five days to peak, so a cat that looks normal an hour later has not necessarily dodged anything. Call a vet or an animal poison control line, and mention what was eaten and roughly how much. For everything else here, the ceiling is small and occasional rather than zero, and the table below is the actual guide to follow, not a blanket rule.',
            'items' => [
                ['name' => 'French fries (plain)', 'verdict' => 'caution', 'note' => 'Cooked potato is not toxic, cooking destroys most of its solanine. The real risk is the oil and salt, and any dip: never offer ketchup, mayo or a seasoned fry, both often hide onion powder.'],
                ['name' => 'Potato chips', 'verdict' => 'caution', 'note' => 'A stray plain chip is not an emergency, no nutrition and roughly 35 to 40 percent fat by weight. Any flavored chip, barbecue, sour cream and onion, ranch, hides onion or garlic powder: skip entirely.'],
                ['name' => 'Pizza (cheese)', 'verdict' => 'caution', 'note' => 'A lick of plain cheese is about the outer limit; most adult cats have reduced lactase and can get loose stool from it. A garlic- or onion-seasoned crust or sauce is a hard no.'],
                ['name' => 'Burger patty (plain, home-cooked)', 'verdict' => 'caution', 'note' => 'The lowest-risk item here if genuinely plain: a thumbnail-sized piece of lean, trimmed beef, cooked at home with no seasoning, given occasionally. Restaurant patties often carry hidden salt or onion powder even when ordered plain.'],
                ['name' => 'Burger (fast food, bun and sauce)', 'verdict' => 'unsafe', 'note' => 'Buns, seasoning blends and sauces like ketchup or special sauce routinely carry onion or garlic powder, genuinely toxic to a cat\'s red blood cells, on top of salt levels far past what a cat handles.'],
                ['name' => 'Fried chicken (breaded)', 'verdict' => 'caution', 'note' => 'Standard breading recipes use onion and garlic powder as base seasoning, not a rare addition. Bone-in pieces can also splinter and injure the throat or gut. Plain meat only, skin, breading and bones removed.'],
                ['name' => 'Soda & soft drinks', 'verdict' => 'unsafe', 'note' => 'Caffeine drives up heart rate and causes tremors and restlessness in cats, and a small body means a small dose goes further. Caffeine-free soda skips that risk but is still sugar water, no nutritional point.'],
                ['name' => 'Candy and chocolate', 'verdict' => 'unsafe', 'note' => 'Chocolate\'s theobromine is a genuine cardiac and neurological toxin, darker chocolate more so, and any real amount is worth a call to a vet. Plain sugar candy is lower-risk but a choking hazard, no upside.'],
                ['name' => 'Ice cream (plain)', 'verdict' => 'caution', 'note' => 'Most adult cats have little of the enzyme needed to digest lactose, so a small lick can bring on loose stool. Any chocolate, coffee or mocha flavor moves this from caution straight to unsafe.'],
            ],
            'watch_for' => [
                'Vomiting, diarrhea or lethargy within hours of a fatty or salty item, most common after fries, chips or a burger patty',
                'Pale or yellow-tinged gums, weakness or dark urine, which can take three to five days to appear after any onion- or garlic-seasoned food',
                'Abdominal pain, hunching or reluctance to be touched near the belly, possible signs of pancreatitis after a fatty meal',
            ],
            'faq' => [
                ['q' => 'Can cats eat fast food?', 'a' => 'No, not as a regular food. Fast food is built around salt, fat and onion or garlic seasoning in the bun, sauce and breading, all genuine risks for a cat. A small taste of something plain, an unsalted fry or a corner of a plain bun, is not an emergency, but nothing on a fast food menu is worth offering on purpose.'],
                ['q' => 'Can cats eat pizza?', 'a' => 'A tiny lick of plain cheese is about as far as pizza safely goes, and even that can cause loose stool in a cat with reduced lactase, common in adult cats. Any slice with a seasoned crust, sauce, pepperoni or sausage should stay off-limits, since onion and garlic powder are common in all four.'],
                ['q' => 'What should I do if my cat eats fast food?', 'a' => 'It depends what was eaten. A plain fry or a corner of a plain bun usually just needs watching for an upset stomach. Anything seasoned, sauced or containing chocolate is different: onion and garlic damage red blood cells over three to five days, and caffeine or theobromine act fast, so call a vet or animal poison control rather than waiting to see.'],
                ['q' => 'Why is fried food especially risky for cats?', 'a' => 'Because of the fat, not the frying itself. A sudden greasy meal is a real trigger for pancreatitis in cats, a painful, inflamed pancreas, and that risk applies whether the fat comes from fries, fried chicken skin or a greasy burger patty.'],
            ],
            'deep_dives' => [
                ['label' => 'Can Cats Eat Cheese?', 'slug' => 'can-cats-eat-cheese'],
                ['label' => 'Can Cats Eat Chicken?', 'slug' => 'can-cats-eat-chicken'],
            ],
        ],
        [
            'slug' => 'herbs-and-spices',
            'published_at' => '2026-08-17',
            'updated_at' => '2026-08-30',
            'title' => 'Herbs & Spices',
            'question' => 'What Spices Can Cats Eat?',
            'answer' => 'Basil and rosemary are fine in small amounts. Onion powder and nutmeg are not, even in a trace hidden in a seasoning blend.',
            'meta_description' => 'Basil and rosemary are safe in a pinch. Onion powder and nutmeg aren\'t, even hidden in a spice blend. See all 15 spices, ranked safe to unsafe.',
            'verdict' => 'caution',
            'note' => 'A few safe, several need caution',
            'image' => 'can-cats-eat-herbs-spices-basil-mint',
            'alt' => 'Basil, mint, rosemary and spice jars beside a cat',
            'why' => "A spice label rarely tells you what actually reaches a cat's bowl, and seasoning is riskier than the plain ingredient for three separate reasons, not one. First, concentration: drying and grinding remove water and pack more of a compound into the same volume, which is why onion or garlic powder is more potent per gram than the fresh vegetable, and why dried basil should be used more sparingly than fresh. Second, cats have a genuinely reduced liver capacity, not folklore: they produce less glucuronyl transferase, the liver enzyme most mammals use to clear plant compounds and essential oils, which is why a spice's essential-oil form, clove and cinnamon oil among them, is consistently a harder hit than the ground spice or fresh leaf. Third, a seasoning is rarely eaten alone. Basil in a skillet usually means garlic or onion nearby, and a spice blend is a label that can carry onion powder without the word ever appearing on a menu. None of that makes every spice dangerous. It means the plain herb and the seasoned dish are two different risk categories, and the dish is usually where the real hazard sits.",
            'guidance' => "For anything marked safe or caution below, keep it to a light sprinkle or a single fresh leaf, not a seasoned dish, and offer it plain, with no oil, salt or sauce layered on top. Fresh generally beats dried for a first try, since drying concentrates a plant's compounds into less volume, so if dried is all you have, use less of it than the fresh amount would call for. Skip essential oils and concentrated extracts entirely: cats clear them far more slowly than the whole herb or ground spice, so a form that looks like a small dose can act like a much larger one. Onion and garlic powder are worth training your eye to catch, since neither word has to appear for either to be present. \"Seasoning,\" \"natural flavor,\" \"spice blend\" and \"granulated\" are common label stand-ins, and gravy, bouillon, pre-made sauce and even some savory baby food, sometimes offered to tempt a sick cat to eat, are frequent carriers. Our <a href=\"/food-guides/vegetables\" class=\"font-semibold text-primary underline decoration-line-strong underline-offset-4\">vegetables guide</a> covers the onion and garlic mechanism in full. When in doubt, read the ingredient list yourself rather than assuming a dish is plain, and treat any food you can't verify as an unknown rather than assuming a small amount makes it safe.",
            'items' => [
                ['name' => 'Basil', 'verdict' => 'safe', 'note' => 'Fine as an occasional fresh leaf or a light sprinkle of dried basil, using less dried since drying concentrates it. Avoid basil essential oil, and watch for garlic or onion in the same dish.'],
                ['name' => 'Rosemary', 'verdict' => 'safe', 'note' => 'Fine as a trace seasoning or fresh sprig. ASPCA lists it non-toxic, and rosemary extract is a common cat-food preservative. Avoid rosemary essential oil, which cats metabolize poorly.'],
                ['name' => 'Catnip', 'verdict' => 'safe', 'note' => 'A pinch of dried catnip, a catnip toy or the fresh plant is safe play, with effects that are temporary and non-addictive per VCA. Avoid concentrated catnip essential oil.'],
                ['name' => 'Parsley', 'verdict' => 'caution', 'note' => 'A garnish-sized fleck of curly or flat-leaf parsley is low-risk. ASPCA lists furanocoumarins that can cause photosensitization, but only from large amounts, so keep it occasional.'],
                ['name' => 'Mint', 'verdict' => 'caution', 'note' => 'ASPCA lists garden mint as toxic via its essential oils, with vomiting and diarrhea tied to large ingestions. A stray fresh leaf is low risk. Never use mint essential oil around a cat.'],
                ['name' => 'Cinnamon', 'verdict' => 'caution', 'note' => 'ASPCA classifies the plant and spice as non-toxic, but larger amounts irritate the throat and stomach, and inhaled loose powder risks coughing or pneumonia. Never use cinnamon essential oil.'],
                ['name' => 'Black pepper', 'verdict' => 'caution', 'note' => 'A stray fleck from your plate isn\'t an emergency. Piperine irritates the gut and airway if used as a regular seasoning. Not classified as toxic by ASPCA or VCA, but still an active irritant.'],
                ['name' => 'Ginger', 'verdict' => 'caution', 'note' => 'A trace in a cat-formulated treat is generally low-risk. Don\'t self-dose it as a remedy, and skip it for cats with gallbladder disease, a bleeding disorder, or anticoagulant or NSAID use.'],
                ['name' => 'Turmeric', 'verdict' => 'caution', 'note' => 'A trace pinch is unlikely to harm a healthy cat, but treat it as a supplement, not a seasoning. Oxalate-rich, so use caution with kidney or bladder-stone history, and skip pairing it with black pepper.'],
                ['name' => 'Cumin', 'verdict' => 'caution', 'note' => 'True cumin is absent from ASPCA\'s, VCA\'s and Cornell\'s toxic lists, though more than a trace can cause vomiting. Never substitute caraway, sold as "Persian cumin," which is toxic via carvone.'],
                ['name' => 'Cayenne & chili powder', 'verdict' => 'caution', 'note' => 'Not a documented poison, but capsaicin burns the mouth, throat and gut, causing drooling and vomiting. Inhaled powder irritates the airway the way pepper spray does.'],
                ['name' => 'Cloves', 'verdict' => 'unsafe', 'note' => 'No established safe dose. Eugenol is a compound cats metabolize poorly, and Pet Poison Helpline names clove among the oils that poison cats. Keep whole, ground and clove oil out of reach.'],
                ['name' => 'Nutmeg', 'verdict' => 'unsafe', 'note' => 'Its toxin, myristicin, can cause vomiting, agitation, pupil changes, a fast heart rate and hallucinations in a large amount, per ASPCA and Pet Poison Helpline.'],
                ['name' => 'Onion powder', 'verdict' => 'unsafe', 'note' => 'No safe amount. The concentrated powder is more potent per gram than fresh onion and causes hemolytic anemia, per ASPCA and Cornell. It hides in broth, gravy and baby food.'],
                ['name' => 'Garlic powder', 'verdict' => 'unsafe', 'note' => 'No safe amount. One teaspoon of powder equals about eight cloves of fresh garlic per VCA, and cats are more Allium-sensitive than dogs. It hides in sauces and seasoning blends.'],
            ],
            'watch_for' => [
                'Pale or yellow gums, weakness, a fast heart rate or reddish urine in the days after onion or garlic powder, signs of the hemolytic anemia both cause',
                'Vomiting, agitation, dilated pupils or a wobbly gait after nutmeg, or drooling, vomiting and lethargy within a day of any concentrated essential oil',
                'Coughing or labored breathing after inhaled cinnamon, black pepper or nutmeg powder, or drooling and pawing at the mouth right after cayenne or chili powder',
            ],
            'faq' => [
                ['q' => 'What spices can cats eat?', 'a' => 'A trace of basil, rosemary or catnip is fine, and a garnish-sized amount of parsley, cinnamon, black pepper, ginger, turmeric or cumin is low-risk on their own. Onion powder, garlic powder, nutmeg and cloves are never safe to feed on purpose, in any amount.'],
                ['q' => 'Is nutmeg toxic to cats?', 'a' => 'Yes, in a large amount. Nutmeg contains myristicin, a compound that can cause vomiting, agitation, pupil changes, a fast heart rate and hallucinations, per ASPCA and Pet Poison Helpline. A trace baked into a treat is unlikely to poison a cat, but there\'s no safe recreational dose, so it\'s never worth seasoning food with on purpose.'],
                ['q' => 'Is cinnamon safe for cats?', 'a' => 'The plant and ground spice are classified non-toxic by ASPCA, but larger amounts irritate the throat and stomach and can raise heart rate, and loose powder can be inhaled and cause coughing or pneumonia. Cinnamon essential oil is a separate, higher-risk category cats metabolize poorly, so keep diffusers and concentrated oil away from a cat entirely.'],
                ['q' => 'How do I know if a spice blend has onion or garlic powder in it?', 'a' => 'Read the ingredient list, not just the front label. "Seasoning," "natural flavor," "spice blend" and "granulated" are common stand-ins for onion or garlic powder, and gravy, bouillon, pre-made sauce and some savory baby food carry it too. If the ingredients aren\'t listed or you can\'t check them, treat the dish as unsafe rather than assuming a small amount is fine.'],
            ],
        ],
        [
            'slug' => 'treats-and-snacks',
            'published_at' => '2026-08-17',
            'updated_at' => '2026-08-25',
            'title' => 'Treats & Snacks',
            'question' => 'Can Cats Eat Treats?',
            'answer' => 'Yes, as long as treats stay under a tenth of daily calories so meals keep their nutrition.',
            'verdict' => 'safe',
            'note' => 'Under 10% of daily calories',
            'image' => 'can-cats-eat-cat-treats-snacks',
            'alt' => 'Cat treats in a white bowl beside a cat',
            'why' => 'Treats are how most training and bonding with a cat actually happens day to day, and there is nothing wrong with that. The risk is not treats themselves, it is scale: a handful of small treats a few times a day adds up faster than it looks, and unlike a measured meal, treats rarely get counted toward a cat\'s daily total.',
            'guidance' => 'The widely used guideline is to keep treats, of any kind, under about ten percent of a cat\'s total daily calories, with the rest coming from a complete, balanced food that is actually formulated to meet their needs. Commercial cat treats are generally formulated to be safe in normal amounts; plain, unseasoned human snacks such as small pieces of cooked meat work as treats too, within the same limit. If you are not sure what your cat\'s daily calorie total actually is, our cat calorie calculator works it out from their weight and activity level, which makes the ten percent limit an actual number rather than a guess.',
            'watch_for' => [
                'Weight gain over a few weeks despite no change in meals, often a sign treats have crept up unnoticed',
                'A cat skipping regular meals in favor of holding out for treats',
            ],
        ],
    ],
];
